const PRODUCTS = [
  {
    "Id": 1,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-analgesic",
    "Name": "DICORREL-MR ",
    "Composition": "Diclofenac Potassium 50mg +Paracetamol 325mg+Chlorzoxazone 250mg",
    "Packing": "10x10 Blister",
    "Mrp": 1150.0,
    "Image-link": "https:\/\/i.ibb.co\/5XXsGVmx\/DICORREL-MR.png",
    "Visual-aid": null
  },
  {
    "Id": 2,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-analgesic",
    "Name": "DICORREL-PS ",
    "Composition": "Diclofenac  Potassium 50mg+ Serratiopeptidase 10mg+Paracetamol  325mg",
    "Packing": "10x10 Blister",
    "Mrp": 1130.0,
    "Image-link": "https:\/\/i.ibb.co\/svThMPzv\/DICORREL-PS.png",
    "Visual-aid": null
  },
  {
    "Id": 3,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-analgesic\/Anti-Asthsmatics",
    "Name": "Montilex-D",
    "Composition": "Montelukast and Desloratadine Tablets",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1650.0,
    "Image-link": "https:\/\/i.ibb.co\/kgnXRKHT\/MONTILEX-D.png",
    "Visual-aid": null
  },
  {
    "Id": 4,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-analgesic\/Anti-Asthsmatics",
    "Name": "LEXOPAN-DSR",
    "Composition": "Pantoprazole Sodium40mg+ Domperidome SR 30mg Cap",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1360.0,
    "Image-link": "https:\/\/i.ibb.co\/Hp1RQ3hd\/LEXOPAN-DSR.png",
    "Visual-aid": null
  },
  {
    "Id": 5,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "LEXACID-LSR",
    "Composition": "Rabeprazole Sodium 20mg+Levosulpiride (sr) 75mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 2150.0,
    "Image-link": "https:\/\/i.ibb.co\/B5ZZHC9N\/LEXACID-LSR.png",
    "Visual-aid": null
  },
  {
    "Id": 6,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-analgesic\/Anti-Asthsmatics",
    "Name": "MONTILEX-L",
    "Composition": "Montelukast Sodium 10mg+Levocetirizine Dihydrochloride 5mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1150.0,
    "Image-link": "https:\/\/i.ibb.co\/Dg16y9Sc\/MONTILEX-L.png",
    "Visual-aid": null
  },
  {
    "Id": 7,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "AMOLEX 625",
    "Composition": "Amoxycillin 500mg+ Potassium Clavulanate 125mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 1965.0,
    "Image-link": "https:\/\/i.ibb.co\/ynp2995K\/AMOLEX-625.png",
    "Visual-aid": null
  },
  {
    "Id": 8,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "BIOROXIM-500",
    "Composition": "Cefuroxime Axetil 500mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 5530.0,
    "Image-link": "https:\/\/i.ibb.co\/GQcvqcRg\/BIOROXIM-500-Tablets.png",
    "Visual-aid": null
  },
  {
    "Id": 9,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "LAXICEF-200 LB ",
    "Composition": "Cefixime Trihydrate200mg + Lactic Acid Bacillus 60 Million Spores",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 1700.0,
    "Image-link": "https:\/\/i.ibb.co\/sJv6prKB\/LAXICEF-200-LB-Tablets.png",
    "Visual-aid": null
  },
  {
    "Id": 10,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "LAXICEF-O",
    "Composition": "Cefixime Trihydrate200mg + Ofloxacin 200mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 1650.0,
    "Image-link": "https:\/\/i.ibb.co\/HZV4vSG\/LAXICEF-O-Tablets.png",
    "Visual-aid": null
  },
  {
    "Id": 11,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "LEXAFLOX ",
    "Composition": "Ofloxacin 200mg",
    "Packing": "10x10 Blister",
    "Mrp": 650.0,
    "Image-link": "https:\/\/i.ibb.co\/tMb0PVGM\/LEXAFLOX.png",
    "Visual-aid": null
  },
  {
    "Id": 12,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "LEXAFLOX OZ ",
    "Composition": "Ofloxacin 200mg+Ornidazole 500mg ",
    "Packing": "10x10 Blister",
    "Mrp": 890.0,
    "Image-link": "https:\/\/i.ibb.co\/qYnCJrzs\/LEXAFLOX-OZ.png",
    "Visual-aid": null
  },
  {
    "Id": 13,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "SENIPOD-200",
    "Composition": "Cefpodoxime Proxetil 200mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 3100.0,
    "Image-link": "https:\/\/i.ibb.co\/0yBhcpLZ\/SINPOD-200-Tablets.png",
    "Visual-aid": null
  },
  {
    "Id": 14,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Fibrinolytic",
    "Name": "HEMOSIL ",
    "Composition": "Tranexamic Acid 500mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 1990.0,
    "Image-link": "https:\/\/i.ibb.co\/bMSsXB9k\/Hemosil.png",
    "Visual-aid": null
  },
  {
    "Id": 15,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Fibrinolytic",
    "Name": "HEMOSIL-M  ",
    "Composition": "Tranexamic Acid 500mg + Mefenamic Acid 250mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 2850.0,
    "Image-link": "https:\/\/i.ibb.co\/h1m4XRxb\/HEMOSIL-M.png",
    "Visual-aid": null
  },
  {
    "Id": 16,
    "Category": "Skin Range ",
    "Sub-category": "OINTMENTS ",
    "Sub-Sub-Category": "Antiseptic & Antibacterial",
    "Name": "MEDISEPT ",
    "Composition": "Povidone Iodine 5%+Ornidazole 1%",
    "Packing": "15GM ",
    "Mrp": 105.0,
    "Image-link": "https:\/\/i.ibb.co\/dw9nW4ZW\/MEDISEPT.png",
    "Visual-aid": null
  },
  {
    "Id": 17,
    "Category": "Skin Range ",
    "Sub-category": "OINTMENTS ",
    "Sub-Sub-Category": "Analgesic",
    "Name": "FLEXA GEL",
    "Composition": "Diclofenac Diethylamine 1.16%w\/w+ Linseed Oil 3% w\/w + Methyl Salicylate 10.%w\/w + Menthol 5%w\/w +Benzyl Alcohol 1%w\/w",
    "Packing": "30gm",
    "Mrp": 105.0,
    "Image-link": "https:\/\/i.ibb.co\/7dKTjs45\/Flexa-gel.png",
    "Visual-aid": null
  },
  {
    "Id": 18,
    "Category": "Orals ",
    "Sub-category": "LIQUID SYRUP ",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "AMOLEX-KID ",
    "Composition": "Amoxycillin 200mg+ Potassium Clavulanate 28.5mg",
    "Packing": "30ml ",
    "Mrp": 65.2,
    "Image-link": "https:\/\/i.ibb.co\/s96SMfzZ\/AMOLEX-KID.png",
    "Visual-aid": null
  },
  {
    "Id": 19,
    "Category": "Orals ",
    "Sub-category": "LIQUID SYRUP ",
    "Sub-Sub-Category": "Appetite Stimulant",
    "Name": "EATWELL",
    "Composition": "Cyproheptadine 2mg with Tricholine Citrate 275mg ",
    "Packing": "200ml",
    "Mrp": 165.0,
    "Image-link": "https:\/\/i.ibb.co\/0yX29KXt\/EATWELL-Syrup.png",
    "Visual-aid": null
  },
  {
    "Id": 20,
    "Category": "Orals ",
    "Sub-category": "LIQUID SYRUP ",
    "Sub-Sub-Category": "CALCIUM & VITAMIN. D3 SUPPLEMENTS",
    "Name": "LEXI DCARE NANO SHOT ",
    "Composition": "Cholecalciferol IP 60000 IU",
    "Packing": "4x5ml ",
    "Mrp": 85.0,
    "Image-link": "https:\/\/i.ibb.co\/jkkt3hNc\/LEXI-DCARE.png",
    "Visual-aid": null
  },
  {
    "Id": 21,
    "Category": "Orals ",
    "Sub-category": "LIQUID SYRUP ",
    "Sub-Sub-Category": "EXPECTORANTS & ANTI TUSSIVE",
    "Name": "LECTUS ",
    "Composition": "Dextromethorphan 10mg+CPM 2mg+Phenylephrine 5mg",
    "Packing": "100ml",
    "Mrp": 82.0,
    "Image-link": "https:\/\/i.ibb.co\/1Yf9FCw9\/Lectus.png",
    "Visual-aid": null
  },
  {
    "Id": 22,
    "Category": "Orals ",
    "Sub-category": "LIQUID SYRUP ",
    "Sub-Sub-Category": "FOOD SUPPLEMENTS",
    "Name": "LEXAONE",
    "Composition": "Antioxidants +Multivitamin+ Multiminral & Cyanobabamin ",
    "Packing": "200ml",
    "Mrp": 148.5,
    "Image-link": "https:\/\/i.ibb.co\/SpbL4sq\/LEXAONE-Syrup.png",
    "Visual-aid": null
  },
  {
    "Id": 23,
    "Category": "Orals ",
    "Sub-category": "DRY SYRUP ",
    "Sub-Sub-Category": "Anti-Biotic",
    "Name": "SINPOD-50",
    "Composition": "Cefpodoxime Proxetil 50mg ",
    "Packing": "30ml ",
    "Mrp": 95.0,
    "Image-link": "https:\/\/i.ibb.co\/MkLtYg7B\/SINPOD-50.png",
    "Visual-aid": null
  },
  {
    "Id": 24,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC\/PROTEOLYTIC",
    "Name": "DICORREL-S ",
    "Composition": "Diclofenac Sodium 50mg+Serratiopeptidase10mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 950.0,
    "Image-link": "https:\/\/i.ibb.co\/3mg7sG4V\/DICORREL-S.png",
    "Visual-aid": null
  },
  {
    "Id": 25,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Pre Pro ",
    "Name": "BIOLECTIK ",
    "Composition": "Lactobacillus acidophilus 75mg+Lactobacillus rhamnosus 75mg+Bifidobacterium longum 75mg+Saccharomyces boulardii 50mg+Fructo-oligo saccharides 100mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 1400.0,
    "Image-link": "https:\/\/i.ibb.co\/1JrtrYNW\/BIOLECTIK.png",
    "Visual-aid": null
  },
  {
    "Id": 26,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "LEXACID-20 ",
    "Composition": "Rabeprazole Sodium 20mg ",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 600.0,
    "Image-link": "https:\/\/i.ibb.co\/gbxX1MhR\/LEXACID-20.png",
    "Visual-aid": null
  },
  {
    "Id": 27,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "LEXACID-D  ",
    "Composition": "Rabeprazole Sodium20mg +Domperidone 10mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 650.0,
    "Image-link": "https:\/\/i.ibb.co\/WW4hs9DW\/Lexacid-D.png",
    "Visual-aid": null
  },
  {
    "Id": 28,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Steriod",
    "Name": "DEFLAXIL",
    "Composition": "Deflazacort 6mg",
    "Packing": "10x10 Alu Alu ",
    "Mrp": 1250.0,
    "Image-link": "https:\/\/i.ibb.co\/CgV7W76\/DEFLAXIL.png",
    "Visual-aid": null
  },
  {
    "Id": 29,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC\/PROTEOLYTIC",
    "Name": "BIOACE-PS",
    "Composition": "Aceclofenac 100mg +Paracetamol 325mg+Serratiopeptidase 15mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1150.0,
    "Image-link": "https:\/\/i.ibb.co\/hJp72XMK\/BIOACE-PS.png",
    "Visual-aid": null
  },
  {
    "Id": 30,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Macrolide-Antibiotic",
    "Name": "AZIOLEX-KIT",
    "Composition": "Azithromycin, Fluconazole with Secnidazole",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1050.0,
    "Image-link": "https:\/\/i.ibb.co\/Kcdg922c\/AZIOLEX-KIT.png",
    "Visual-aid": null
  },
  {
    "Id": 31,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "LAXOPAN -40",
    "Composition": "Pantoprazole -40mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 730.0,
    "Image-link": "https:\/\/i.ibb.co\/prxZ4k4C\/LAXOPAN-40.png",
    "Visual-aid": null
  },
  {
    "Id": 32,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Antihistamine",
    "Name": "DESLOLEX",
    "Composition": "Desloratadine 5mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 775.0,
    "Image-link": "https:\/\/i.ibb.co\/Gvv44HJL\/DESLOLEX.png",
    "Visual-aid": null
  },
  {
    "Id": 33,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC\/PROTEOLYTIC",
    "Name": "BIOACE-P",
    "Composition": "Aceclofenac 100mg +Paracetamol 325mg",
    "Packing": "20X10 Blister",
    "Mrp": 1100.0,
    "Image-link": "https:\/\/i.ibb.co\/Z6NJc7Gv\/BIOACE-P.png",
    "Visual-aid": null
  },
  {
    "Id": 34,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC\/PROTEOLYTIC",
    "Name": "BIOACE-MR",
    "Composition": "Aceclofenac 100mg +Paracetamol 325mg+Chlorzoxazone 250mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 730.0,
    "Image-link": "https:\/\/i.ibb.co\/HL7dLBKz\/BIOACE-MR.png",
    "Visual-aid": null
  },
  {
    "Id": 35,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "ESOLEX",
    "Composition": "Esomeprazole 40mg+ Domperodone 30mg SR.",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1250.0,
    "Image-link": "https:\/\/i.ibb.co\/gLPcn8DJ\/ESOLEX.png",
    "Visual-aid": null
  },
  {
    "Id": 36,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "Anti-Spasmodic",
    "Name": "LEXSPAS-AC",
    "Composition": "Drotaverine HCl 80mg + Aceclofenac 100mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1040.0,
    "Image-link": "https:\/\/i.ibb.co\/Kj0GpKcB\/LEXSPAS-AC.png",
    "Visual-aid": null
  },
  {
    "Id": 37,
    "Category": "PROTEIN POWDER",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "FOOD SUPPLEMENTS",
    "Name": "PROLEXA",
    "Composition": "Fortified With Protein Vitamin & Minerals (VANILA FLAVOUR)",
    "Packing": "200gm",
    "Mrp": 280.0,
    "Image-link": "https:\/\/i.ibb.co\/Z6NbxY9p\/PROLEXA.png",
    "Visual-aid": null
  },
  {
    "Id": 38,
    "Category": "Orals ",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "HEAMHEAMATINICS",
    "Name": "LEFIFER ",
    "Composition": "Ferrous Ascorbate 100mg+Folic Acid 1.5mg",
    "Packing": "10x10 Alu Alu",
    "Mrp": 1050.0,
    "Image-link": "https:\/\/i.ibb.co\/k2VWVh1L\/LEXIFER.png",
    "Visual-aid": null
  },
  {
    "Id": 39,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "CEFOLEX-S1GM",
    "Composition": "Cefoperazone Sodium 500mg with Sulbactam 500mg",
    "Packing": "Vial Pack",
    "Mrp": 205.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=CEFOLEX-S1GM",
    "Visual-aid": null
  },
  {
    "Id": 40,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "CEFOLEX-S1.5GM",
    "Composition": "Cefoperazone Sodium 1000mg with Sulbactam 500mg",
    "Packing": "Vial Pack",
    "Mrp": 260.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=CEFOLEX-S1.5GM",
    "Visual-aid": null
  },
  {
    "Id": 41,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "CEFOLEX-XP1125",
    "Composition": "Cefoperazone Sodium 1000mg with Tazobactam 125mg",
    "Packing": "Vial Pack",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=CEFOLEX-XP1125",
    "Visual-aid": null
  },
  {
    "Id": 42,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "TAZILEXIM-TZ 1125",
    "Composition": "Ceftazidime 1000mg with Tazobactam 125mg",
    "Packing": "Vial Pack",
    "Mrp": 410.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=TAZILEXIM-TZ%201125",
    "Visual-aid": null
  },
  {
    "Id": 43,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "TAZILEXIM-TZ 281.25",
    "Composition": "Ceftazidime 250mg with Tazobactam 31.25mg",
    "Packing": "Vial Pack",
    "Mrp": 102.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=TAZILEXIM-TZ%20281.25",
    "Visual-aid": null
  },
  {
    "Id": 44,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "TAZILEXIM 250MG",
    "Composition": "Ceftazidime 250mg",
    "Packing": "Vial Pack",
    "Mrp": 85.01,
    "Image-link": "https:\/\/placehold.co\/400x400?text=TAZILEXIM%20250MG",
    "Visual-aid": null
  },
  {
    "Id": 45,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "TAZILEXIM 1GM",
    "Composition": "Ceftazidime 1000mg",
    "Packing": "Vial Pack",
    "Mrp": 244.09,
    "Image-link": "https:\/\/placehold.co\/400x400?text=TAZILEXIM%201GM",
    "Visual-aid": null
  },
  {
    "Id": 46,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXONE-1GM",
    "Composition": "Ceftriaxone Sodium 1000mg",
    "Packing": "Vial Pack",
    "Mrp": 67.07,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXONE-1GM",
    "Visual-aid": null
  },
  {
    "Id": 47,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXONE-500GM",
    "Composition": "Ceftriaxone Sodium 500mg",
    "Packing": "Vial Pack",
    "Mrp": 54.06,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXONE-500GM",
    "Visual-aid": null
  },
  {
    "Id": 48,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXONE-250GM",
    "Composition": "Ceftriaxone Sodium 250mg",
    "Packing": "Vial Pack",
    "Mrp": 30.47,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXONE-250GM",
    "Visual-aid": null
  },
  {
    "Id": 49,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXON-S1.5mg",
    "Composition": "Ceftriaxone Sodium 250mg with Sulbactam 125mg per vial",
    "Packing": "Vial Pack",
    "Mrp": 148.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXON-S1.5mg",
    "Visual-aid": null
  },
  {
    "Id": 50,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXON-TZ 1125mg",
    "Composition": "Ceftriaxone Sodium 1000mg with Tazobactam 1125mg per vial",
    "Packing": "Vial Pack",
    "Mrp": 244.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXON-TZ%201125mg",
    "Visual-aid": null
  },
  {
    "Id": 51,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXON-TZ 281.25mg",
    "Composition": "Ceftriaxone Sodium 250mg with Tazobactam 31.25mg",
    "Packing": "Vial Pack",
    "Mrp": 108.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXON-TZ%20281.25mg",
    "Visual-aid": null
  },
  {
    "Id": 52,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEFUROX-250",
    "Composition": "Cefuroxime Sodium 250mg",
    "Packing": "Vial Pack",
    "Mrp": 115.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEFUROX-250",
    "Visual-aid": null
  },
  {
    "Id": 53,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEFUROX-1500",
    "Composition": "Cefuroxime Sodium 1500mg",
    "Packing": "Vial Pack",
    "Mrp": 364.24,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEFUROX-1500",
    "Visual-aid": null
  },
  {
    "Id": 54,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "LESOP",
    "Composition": "Esomeprazole 40mg",
    "Packing": "Vial Pack",
    "Mrp": 160.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LESOP",
    "Visual-aid": null
  },
  {
    "Id": 55,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "STEROIDS",
    "Name": "LEKORT-100",
    "Composition": "Hydrocortisone Sodium Succinate 100mg",
    "Packing": "Vial Pack",
    "Mrp": 48.16,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEKORT-100",
    "Visual-aid": null
  },
  {
    "Id": 56,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "STEROIDS",
    "Name": "LEKORT-200",
    "Composition": "Hydrocortisone Sodium Succinate 200mg",
    "Packing": "Vial Pack",
    "Mrp": 70.82,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEKORT-200",
    "Visual-aid": null
  },
  {
    "Id": 57,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXOPENAM-1GM",
    "Composition": "Meropenem 1gm",
    "Packing": "Vial Pack",
    "Mrp": 1024.4,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXOPENAM-1GM",
    "Visual-aid": null
  },
  {
    "Id": 58,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
    "Name": "LEXOPAN-40 (Injection)",
    "Composition": "Pantoprazole 40mg",
    "Packing": "Vial Pack",
    "Mrp": 24.24,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXOPAN-40%20%28Injection%29",
    "Visual-aid": null
  },
  {
    "Id": 59,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LE-PTAZ 1125",
    "Composition": "Piperacillin 1000mg with Tazobactam 125mg",
    "Packing": "Vial Pack",
    "Mrp": 107.15,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LE-PTAZ%201125",
    "Visual-aid": null
  },
  {
    "Id": 60,
    "Category": "INJECTIONS",
    "Sub-category": "Liquid Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LE-PTAZ 4500",
    "Composition": "Piperacillin 4000mg with Tazobactam 500mg",
    "Packing": "Vial Pack",
    "Mrp": 429.75,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LE-PTAZ%204500",
    "Visual-aid": null
  },
  {
    "Id": 61,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXAMIN-100",
    "Composition": "Amikacin Sulphate 100mg",
    "Packing": "2ml Vial Pack",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXAMIN-100",
    "Visual-aid": null
  },
  {
    "Id": 62,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXAMIN-250",
    "Composition": "Amikacin Sulphate 250mg",
    "Packing": "2ml Vial Pack",
    "Mrp": 58.24,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXAMIN-250",
    "Visual-aid": null
  },
  {
    "Id": 63,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "LEXAMIN-500",
    "Composition": "Amikacin Sulphate 500mg",
    "Packing": "2ml Vial Pack",
    "Mrp": 115.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXAMIN-500",
    "Visual-aid": null
  },
  {
    "Id": 64,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": null,
    "Name": "CITILEX-250",
    "Composition": "Citicoline 250mg",
    "Packing": "2ml Ampoule",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=CITILEX-250",
    "Visual-aid": null
  },
  {
    "Id": 65,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-BACTERIAL",
    "Name": "BIOCLIN",
    "Composition": "Clindamycin Phosphate 150mg",
    "Packing": "1x2ml Ampoule",
    "Mrp": 130.3,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BIOCLIN",
    "Visual-aid": null
  },
  {
    "Id": 66,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "STEROIDS",
    "Name": "LEDEX",
    "Composition": "Dexamethasone Sodium Phosphate 4mg",
    "Packing": "100x2ml Vial Pack",
    "Mrp": 10.94,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEDEX",
    "Visual-aid": null
  },
  {
    "Id": 67,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC",
    "Name": "DICORREL (Injection)",
    "Composition": "Diclofenac Sodium 75mg",
    "Packing": "100x1ml Ampoule",
    "Mrp": 21.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=DICORREL%20%28Injection%29",
    "Visual-aid": null
  },
  {
    "Id": 68,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTISPASMODIC",
    "Name": "LEXSPAS (Injection)",
    "Composition": "Drotaverine Hydrochloride 20mg",
    "Packing": "10x2ml Ampoule",
    "Mrp": 25.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXSPAS%20%28Injection%29",
    "Visual-aid": null
  },
  {
    "Id": 69,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": null,
    "Name": "GENTALEX",
    "Composition": "Gentamicin Sulphate 40mg",
    "Packing": "100x2ml Ampoule",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=GENTALEX",
    "Visual-aid": null
  },
  {
    "Id": 70,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-EMETIC",
    "Name": "GRALEX",
    "Composition": "Granisetron Hcl 1mg\/ml",
    "Packing": "3ml Vial Pack",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=GRALEX",
    "Visual-aid": null
  },
  {
    "Id": 71,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "HARMONES",
    "Name": "PRO-DEPOT-250",
    "Composition": "Hydroxyprogesterone 250mg",
    "Packing": "1x1ml Ampoule",
    "Mrp": 165.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=PRO-DEPOT-250",
    "Visual-aid": null
  },
  {
    "Id": 72,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "HARMONES",
    "Name": "PRO-DEPOT-500",
    "Composition": "Hydroxyprogesterone 500mg",
    "Packing": "1x2ml Ampoule",
    "Mrp": 270.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=PRO-DEPOT-500",
    "Visual-aid": null
  },
  {
    "Id": 73,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "HEAEMATINICS",
    "Name": "LEXAFER (Injection)",
    "Composition": "Iron Sucrose 20mg",
    "Packing": "1x5ml Ampoule",
    "Mrp": 308.64,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXAFER%20%28Injection%29",
    "Visual-aid": null
  },
  {
    "Id": 74,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC",
    "Name": "LEXET",
    "Composition": "Ketorolac Tromethamine 30mg",
    "Packing": "5x1ml Ampoule",
    "Mrp": 22.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXET",
    "Visual-aid": null
  },
  {
    "Id": 75,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "VITAMIN SUPPLEMENTS",
    "Name": "LEXO-B12",
    "Composition": "Mecobalamin 1000mcg",
    "Packing": "5x1ml Ampoule (Blister Pack)",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXO-B12",
    "Visual-aid": null
  },
  {
    "Id": 76,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "VITAMIN SUPPLEMENTS",
    "Name": "LEXO-B12 Plus",
    "Composition": "Methylcobalamin 1000mcg+Nicotinamide 100mg+Pyridoxine HCl 100mg",
    "Packing": "1x2ml Ampoule (Dispo Pack)",
    "Mrp": 80.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXO-B12%20Plus",
    "Visual-aid": null
  },
  {
    "Id": 77,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "VITAMIN SUPPLEMENTS",
    "Name": "Lexo 12 Forte",
    "Composition": "Methylcobalamin 2500mcg+Folic acid 0.7mg+Niacinamide 12mg+Vitamin C 150mg",
    "Packing": "Combi Pack",
    "Mrp": 110.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Lexo%2012%20Forte",
    "Visual-aid": null
  },
  {
    "Id": 78,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": null,
    "Name": "LEXOPRED-40mg",
    "Composition": "Methylprednisolone Acetate 40mg\/ml",
    "Packing": "2ml Vial Pack",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXOPRED-40mg",
    "Visual-aid": null
  },
  {
    "Id": 79,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "STEROIDS",
    "Name": "LEXIDEC-25",
    "Composition": "Nandrolone Decanoate 25mg",
    "Packing": "1x1ml Ampoule (Dispo Pack)",
    "Mrp": 135.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXIDEC-25",
    "Visual-aid": null
  },
  {
    "Id": 80,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "STEROIDS",
    "Name": "LEXIDEC-50",
    "Composition": "Nandrolone Decanoate 50mg",
    "Packing": "1x1ml Ampoule (Dispo Pack)",
    "Mrp": 170.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXIDEC-50",
    "Visual-aid": null
  },
  {
    "Id": 81,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-EMETIC",
    "Name": "BIODAN",
    "Composition": "Ondansetron 2mg",
    "Packing": "10x2ml Ampoule",
    "Mrp": 12.81,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BIODAN",
    "Visual-aid": null
  },
  {
    "Id": 82,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC",
    "Name": "LEROXI",
    "Composition": "Piroxicam 20mg",
    "Packing": "10x2ml Ampoule",
    "Mrp": 30.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEROXI",
    "Visual-aid": null
  },
  {
    "Id": 83,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "ANTI-FIBRINOLYTIC",
    "Name": "LEXIMIC",
    "Composition": "Tranexamic Acid 100mg",
    "Packing": "5x5ml Ampoule",
    "Mrp": 73.71,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXIMIC",
    "Visual-aid": null
  },
  {
    "Id": 84,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "STEROIDS",
    "Name": "LEXICORT-40",
    "Composition": "Triamcinolone Acetonide 40mg",
    "Packing": "2ml Vial Pack",
    "Mrp": 135.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXICORT-40",
    "Visual-aid": null
  },
  {
    "Id": 85,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "VITAMIN SUPPLEMENTS",
    "Name": "LEXCICAL-MAX",
    "Composition": "Vitamin B12 50mcg+Calcium Gluconolactobionate 137.5mg+Vitamin D3 5000 i.u.+Benzyl Alcohol 1.5%v\/v",
    "Packing": "5x3ml Ampoule",
    "Mrp": 65.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXCICAL-MAX",
    "Visual-aid": null
  },
  {
    "Id": 86,
    "Category": "INJECTIONS",
    "Sub-category": "Dry Injection",
    "Sub-Sub-Category": "VITAMIN SUPPLEMENTS",
    "Name": "LEXI DCARE (Injection)",
    "Composition": "Vitamin D3 600000 i.u.",
    "Packing": "5x1ml Ampoule",
    "Mrp": 70.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXI%20DCARE%20%28Injection%29",
    "Visual-aid": null
  },
  {
    "Id": 87,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "EYELEXA Tears Eye Drop",
    "Composition": "Carboxymethylcellulose 0.5% with SOC",
    "Packing": "10ml Vial",
    "Mrp": 132.19,
    "Image-link": "https:\/\/placehold.co\/400x400?text=EYELEXA%20Tears%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 88,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "EYELEXA Tears gel Eye Drop",
    "Composition": "Carboxymethylcellulose 1% with SOC",
    "Packing": "10ml Vial",
    "Mrp": 178.29,
    "Image-link": "https:\/\/placehold.co\/400x400?text=EYELEXA%20Tears%20gel%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 89,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "BioTears-Lxe Eye Drop",
    "Composition": "Carboxymethylcellulose 0.5%, Glycerin 0.5% with SOC",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BioTears-Lxe%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 90,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": null,
    "Name": "HydroTears Eye Drop",
    "Composition": "HPMC 0.3% with Sodium Perborate",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=HydroTears%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 91,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "LexaClear Eye Drop",
    "Composition": "Naphazoline Hcl 0.05%, Chlorpheniramine 0.01%, CMC 0.2%, Camphor 0.01% with SOC",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LexaClear%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 92,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "Povilexa Eye Drop",
    "Composition": "Polyethylene Glycol 0.4% with Propylene 0.3%",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Povilexa%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 93,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "Hyra-LX Eye Drop",
    "Composition": "Sodium Hyaluronate 0.1% with SOC",
    "Packing": "10ml Vial",
    "Mrp": 435.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Hyra-LX%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 94,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "SOOTHING AGENT",
    "Name": "Hyra-L 400 Eye Drop",
    "Composition": "Sodium Hyaluronate 0.15%, PG 400 0.4%, PG 0.3%",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Hyra-L%20400%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 95,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "Gatilexa Eye Drop",
    "Composition": "Gatifloxacin 0.3% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 60.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Gatilexa%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 96,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "Moxilexa Eye Drop",
    "Composition": "Moxifloxacin 0.5%",
    "Packing": "5ml Vial",
    "Mrp": 130.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Moxilexa%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 97,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "Oorex Eye Drop",
    "Composition": "Ofloxacin 0.3%, HPMC 0.025% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Oorex%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 98,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "Tobrix Eye Drop",
    "Composition": "Tobramycin Sulphate 0.3% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 80.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Tobrix%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 99,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-FUNGAL",
    "Name": "Natylexa Eye Drop",
    "Composition": "Natamycin 5% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Natylexa%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 100,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": null,
    "Name": "Ketolexa Eye Drop",
    "Composition": "Ketorolac Tromethamine 0.5%, HPMC 0.025% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Ketolexa%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 101,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-INFLAMMATORY & ANALGESIC",
    "Name": "Nepalex Eye Drop",
    "Composition": "Nepafenac 0.1% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Nepalex%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 102,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": null,
    "Name": "BromliXa Eye Drop",
    "Composition": "Bromfenac Sodium 0.09% + BKC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BromliXa%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 103,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-INFLAMMATORY & ANALGESIC",
    "Name": "Nepax Eye Drop",
    "Composition": "Nepafenac 0.1% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 145.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Nepax%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 104,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "CORTICOSTEROIDS",
    "Name": "Loteprex Eye Drop",
    "Composition": "Loteprednol Etabonate 0.5% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 140.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Loteprex%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 105,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "CORTICOSTEROIDS",
    "Name": "Flulex Eye Drop",
    "Composition": "Fluorometholone 0.1% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 110.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Flulex%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 106,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": null,
    "Name": "Prednix Eye Drop",
    "Composition": "Prednisolone Acetate 1% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=Prednix%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 107,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-ALLERGIC",
    "Name": "OLOPRIX Eye Drop",
    "Composition": "Olopatadine Hydrochloride 0.1% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 140.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=OLOPRIX%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 108,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": null,
    "Name": "BEPOLEX Eye Drop",
    "Composition": "Bepotastine Besilate 1.5% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BEPOLEX%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 109,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-GLAUCOMA",
    "Name": "TIMEXA Eye Drop",
    "Composition": "Timolol Maleate 0.5% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 72.03,
    "Image-link": "https:\/\/placehold.co\/400x400?text=TIMEXA%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 110,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-GLAUCOMA",
    "Name": "TRAVOLEX Eye Drop",
    "Composition": "Travoprost 0.004% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=TRAVOLEX%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 111,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": null,
    "Name": "CAT-Lex Eye Drop",
    "Composition": "Potassium Iodide 3.3%, Calcium Chloride 1%, Sodium Chloride 0.83% with MP & PP",
    "Packing": "5ml Vial",
    "Mrp": 65.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=CAT-Lex%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 112,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "EAR DROPS ANTI FUNGAL\/ANTI BACTERIAL",
    "Name": "OTOLEXA Ear Drops",
    "Composition": "Chloramphenicol 5%, Beclomethasone 0.025%, Clotrimazole 1%, Glycerine 2% with PG",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=OTOLEXA%20Ear%20Drops",
    "Visual-aid": null
  },
  {
    "Id": 113,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "DENTAL RANGE",
    "Name": "CLOTIX Ear Drop",
    "Composition": "Clotrimazole 1% with Lignocaine 2% with PG",
    "Packing": "5ml Vial",
    "Mrp": 105.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=CLOTIX%20Ear%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 114,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "EAR DROPS ANTI FUNGAL\/ANTI BACTERIAL",
    "Name": "WAXOLEX Eye Drop",
    "Composition": "Paradichlorobenzene 2%, Benzocaine 2.7%, Chlorbutol 5%, Turpentine Oil 15% with oily base",
    "Packing": "10ml Vial",
    "Mrp": 120.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=WAXOLEX%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 115,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "MOXILEX-K Eye Drop",
    "Composition": "Moxifloxacin 0.5% with Ketorolac 0.4% with SOC",
    "Packing": "10ml Vial",
    "Mrp": 140.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MOXILEX-K%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 116,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "MOXILEX-LP Eye Drop",
    "Composition": "Moxifloxacin 0.5% with Loteprednol Etabonate 0.5% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 195.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MOXILEX-LP%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 117,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "MOXILEX-DX Eye Drop",
    "Composition": "Moxifloxacin 0.5%, Dexamethasone 0.01% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 130.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MOXILEX-DX%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 118,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "MOXILEX-T Eye Drop",
    "Composition": "Moxifloxacin 0.5%, Tobramycin 0.3% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MOXILEX-T%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 119,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "GATILEX-P Eye Drop",
    "Composition": "Gatifloxacin 0.3%, Prednisolone Acetate 1% with BKC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=GATILEX-P%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 120,
    "Category": "DROPS",
    "Sub-category": "Eye\/Ear Drops",
    "Sub-Sub-Category": "ALPHA ADRENERGIC AGONIST",
    "Name": "BRIMEXA-T Eye Drop",
    "Composition": "Brimonidine Tartrate 0.2% & Timolol Maleate 0.5% with SOC",
    "Packing": "5ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BRIMEXA-T%20Eye%20Drop",
    "Visual-aid": null
  },
  {
    "Id": 121,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": "ANTI CONGESTION & INFECTION",
    "Name": "XYLOLEX Nasal Spray",
    "Composition": "Xylometazoline Hcl 0.05% NS",
    "Packing": "10ml Vial",
    "Mrp": 45.04,
    "Image-link": "https:\/\/placehold.co\/400x400?text=XYLOLEX%20Nasal%20Spray",
    "Visual-aid": null
  },
  {
    "Id": 122,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": "ANTI CONGESTION & INFECTION",
    "Name": "XYLOLEX-A Nasal Spray",
    "Composition": "Xylometazoline Hcl 0.1% NS",
    "Packing": "10ml Vial",
    "Mrp": 55.02,
    "Image-link": "https:\/\/placehold.co\/400x400?text=XYLOLEX-A%20Nasal%20Spray",
    "Visual-aid": null
  },
  {
    "Id": 123,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": null,
    "Name": "SALEXA Nasal Spray",
    "Composition": "Sodium Chloride 0.65% NS",
    "Packing": "15ml Vial",
    "Mrp": 80.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=SALEXA%20Nasal%20Spray",
    "Visual-aid": null
  },
  {
    "Id": 124,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": null,
    "Name": "OXYLEX Nasal Spray (0.01%)",
    "Composition": "Oxymetazoline Hcl 0.01% with BKC NS",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=OXYLEX%20Nasal%20Spray%20%280.01%25%29",
    "Visual-aid": null
  },
  {
    "Id": 125,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": null,
    "Name": "OXYLEX Nasal Spray (0.05%)",
    "Composition": "Oxymetazoline Hcl 0.05% with BKC NS",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=OXYLEX%20Nasal%20Spray%20%280.05%25%29",
    "Visual-aid": null
  },
  {
    "Id": 126,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": "ANTI CONGESTION & INFECTION",
    "Name": "MOLEX Nasal Spray",
    "Composition": "Mometasone Furoate 50mcg with BKC NS",
    "Packing": "10ml Vial",
    "Mrp": 340.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MOLEX%20Nasal%20Spray",
    "Visual-aid": null
  },
  {
    "Id": 127,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": "ANTI CONGESTION & INFECTION",
    "Name": "FLUTOREX Nasal Spray",
    "Composition": "Fluticasone Furoate 27.5mcg (0.055%) with BKC NS",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=FLUTOREX%20Nasal%20Spray",
    "Visual-aid": null
  },
  {
    "Id": 128,
    "Category": "Sprays",
    "Sub-category": "Nasal Drops\/Spray",
    "Sub-Sub-Category": "ANTI CONGESTION & INFECTION",
    "Name": "FLUTOREX-A Nasal Spray",
    "Composition": "Azelastine Hcl 0.14%, Fluticasone Propionate 0.05% with BKC NS",
    "Packing": "10ml Vial",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=FLUTOREX-A%20Nasal%20Spray",
    "Visual-aid": null
  },
  {
    "Id": 129,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "NSAIDS\/ANALGESIC\/PROTEOLYTIC",
    "Name": "BIOACE-PTH4",
    "Composition": "Aceclofenac 100mg+Paracetamol 325mg+Thiocolchicoside 4mg",
    "Packing": "10x10A",
    "Mrp": 3750.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BIOACE-PTH4",
    "Visual-aid": null
  },
  {
    "Id": 130,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "AZIOLEX-250",
    "Composition": "Azithromycin Dihydrate 250mg",
    "Packing": "10X6B",
    "Mrp": 752.85,
    "Image-link": "https:\/\/placehold.co\/400x400?text=AZIOLEX-250",
    "Visual-aid": null
  },
  {
    "Id": 131,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "AZIOLEX-500",
    "Composition": "Azithromycin Dihydrate 500mg",
    "Packing": "10X5B",
    "Mrp": 1267.35,
    "Image-link": "https:\/\/placehold.co\/400x400?text=AZIOLEX-500",
    "Visual-aid": null
  },
  {
    "Id": 132,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI- ALLERGIC\/ANTI ASTHMATICS",
    "Name": "BIOZENO",
    "Composition": "Levocetirizine Dihydrochloride 5mg",
    "Packing": "10X10A",
    "Mrp": 465.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=BIOZENO",
    "Visual-aid": null
  },
  {
    "Id": 133,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI- ALLERGIC\/ANTI ASTHMATICS",
    "Name": "MONTILEX-F",
    "Composition": "Montelukast 10mg with Fexofenadine 120mg",
    "Packing": "10X10A",
    "Mrp": 1500.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MONTILEX-F",
    "Visual-aid": null
  },
  {
    "Id": 134,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI- ALLERGIC\/ANTI ASTHMATICS",
    "Name": "MONTILEX-BL",
    "Composition": "Montelukast Sodium 10mg+Bilastine 20mg",
    "Packing": "10X10A",
    "Mrp": 1860.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=MONTILEX-BL",
    "Visual-aid": null
  },
  {
    "Id": 135,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "MULTIVITAMIN",
    "Name": "LEXAONE (Tablet)",
    "Composition": "Multivitamin Tablet",
    "Packing": "10x10A",
    "Mrp": 900.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXAONE%20%28Tablet%29",
    "Visual-aid": null
  },
  {
    "Id": 136,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "SENIPOD-100",
    "Composition": "Cefpodoxime Proxetil 100mg",
    "Packing": "10x10A",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=SENIPOD-100",
    "Visual-aid": null
  },
  {
    "Id": 137,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI-BIOTIC",
    "Name": "SENIPOD-O",
    "Composition": "Cefpodoxime Proxetil 200mg with Ofloxacin 200mg",
    "Packing": "10x10A",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=SENIPOD-O",
    "Visual-aid": null
  },
  {
    "Id": 138,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": null,
    "Name": "LEXONID",
    "Composition": "Linezolid 600mg",
    "Packing": "10x10",
    "Mrp": 0.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=LEXONID",
    "Visual-aid": null
  },
  {
    "Id": 139,
    "Category": "Orals",
    "Sub-category": "TABLETS",
    "Sub-Sub-Category": "ANTI- ALLERGIC\/ANTI ASTHMATICS",
    "Name": "COLDLEX",
    "Composition": "Paracetamol 500mg+Phenylephrine Hcl 5mg+Calcium 300mg with Diphenhydramine",
    "Packing": "10x10A",
    "Mrp": 650.0,
    "Image-link": "https:\/\/placehold.co\/400x400?text=COLDLEX",
    "Visual-aid": null
  }
]

export default PRODUCTS;