const PRODUCTS = [{
        "Id": 1,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ACRID ",
        "Composition": "Clindamycin Phosphate 150 mg/ml 2ml INJECTION",
        "Packing": "1x2ml Ampoule",
        "Mrp": 113.0,
        "Image-link": "https://i.ibb.co/3ZcvBSY/Acrid-1-2ml.png",
        "Visual-aid": "https://i.ibb.co/wF8SwHkk/OH-35-ACRID-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 2,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ΟΙΝ-500 ",
        "Composition": "Amikacin Sulphate 500 mg INJECTION",
        "Packing": "2ml Vial ",
        "Mrp": 104.0,
        "Image-link": "https://i.ibb.co/sJvWJHRZ/Oin-500-2ml.png",
        "Visual-aid": null
    },
    {
        "Id": 3,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "ANTI-EMETIC",
        "Name": "ODESTRON ",
        "Composition": "Ondansetron 2 mg/ml INJECTION",
        "Packing": "10x2ml Ampoule",
        "Mrp": 12.5,
        "Image-link": "https://i.ibb.co/F4vqZkDp/Odestron-2ml.png",
        "Visual-aid": "https://i.ibb.co/bYYdHmy/OH-28-ODESTRON-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 4,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "ANTI-FIBRINOLYTIC",
        "Name": "NEXIC ",
        "Composition": "Tranexamic Acıd 500 mg/ml INJECTION",
        "Packing": "5X5ml Ampoule",
        "Mrp": 73.22,
        "Image-link": "https://i.ibb.co/xKcMJBN3/Nexic-5-5ml.png",
        "Visual-aid": "https://i.ibb.co/Z66hnS8L/OH-30-NEXIC-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 5,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "ANTI-MALARIAL ",
        "Name": "ALFADIN ",
        "Composition": "Arteether-150  INJECTION",
        "Packing": "1x2ml Dispo Pack",
        "Mrp": 93.0,
        "Image-link": "https://i.ibb.co/zhv7KYPL/Alfadin-1-2-ML.png",
        "Visual-aid": "https://i.ibb.co/1Y7K9jrG/OH-1-ALFADIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 6,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "HAEMATINICS",
        "Name": "FEROROFER ",
        "Composition": "Iron Sucrose 20 mg (2.5ml,5ml) INJECTION",
        "Packing": "1x5ml Ampoule",
        "Mrp": 300.0,
        "Image-link": "https://i.ibb.co/pvLCVZtq/Ferorofer-1-5ml.png",
        "Visual-aid": "https://i.ibb.co/ZpFT9LrX/OH-4-FEROROFER-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 7,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "HORMONES",
        "Name": "PRODIN DEPOT-500 ",
        "Composition": "Hydroxyprogesterone 500mg INJECTION",
        "Packing": "1x1ml Dispo Pack ",
        "Mrp": 237.19,
        "Image-link": "https://i.ibb.co/0pXDNhRM/Prodin-Depot-500.png",
        "Visual-aid": "https://i.ibb.co/ZpJ3dKsg/OH-23-PRODIN-DEPOT-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 8,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "NSAID/ANALGESIC",
        "Name": "DILON-AQ ",
        "Composition": "Diclofenac Sodium 75 mg/ml INJECTION",
        "Packing": "10x5x1ml Ampoule",
        "Mrp": 19.0,
        "Image-link": "https://i.ibb.co/zTxZQ0Q8/Dilon-AQ-10-5-1ml.png",
        "Visual-aid": "https://i.ibb.co/KxZvTVck/OH-32-DILON-AQ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 9,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "NSAID/ANALGESIC",
        "Name": "GENMOL",
        "Composition": "Paracetamol 150 mg/ml INJECTION",
        "Packing": "10x2ml Ampoule ",
        "Mrp": 7.22,
        "Image-link": "https://i.ibb.co/208p3hsd/Genmol-10-2ml.png",
        "Visual-aid": null
    },
    {
        "Id": 10,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "NSAID/ANALGESIC",
        "Name": "KI-INJ ",
        "Composition": "Ketorolac Tromethamine 30 mg/ml INJECTION",
        "Packing": "5x1ml Ampoule",
        "Mrp": 20.0,
        "Image-link": "https://i.ibb.co/v4gQh0JH/Ki-Inj-5-1ml.png",
        "Visual-aid": "https://i.ibb.co/7tDzYjwL/OH-31-KI-INJ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 11,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "NSAID/ANALGESIC",
        "Name": "PIRODIN ",
        "Composition": "Piroxicam 20mg/ml INJECTION",
        "Packing": "10x2ml Ampoule",
        "Mrp": 27.19,
        "Image-link": "https://i.ibb.co/fGH0g38Q/Pirodin-10-2ml.png",
        "Visual-aid": "https://i.ibb.co/dw3zmZgp/OH-24-PIRODIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 12,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "OD-DEX ",
        "Composition": "Dexamethasone Sodium Phosphate 4mg INJECTION",
        "Packing": "2ml Vial ",
        "Mrp": 10.88,
        "Image-link": "https://i.ibb.co/QFr93gV3/OD-DEX.png",
        "Visual-aid": null
    },
    {
        "Id": 13,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "ONEDEC-25",
        "Composition": "nulldrolone Decanoate 25mg INJECTION",
        "Packing": "1x1ml Dispo Pack ",
        "Mrp": 121.0,
        "Image-link": "https://i.ibb.co/ks4rzbHR/Onedec-25-1ml.png",
        "Visual-aid": "https://i.ibb.co/chZYCffJ/OH-3-ONEDEC-25-50-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 14,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "ONEDEC-50",
        "Composition": "nulldrolone Decanoate 50 mg INJECTION",
        "Packing": "1x1ml Dispo Pack ",
        "Mrp": 154.0,
        "Image-link": "https://i.ibb.co/1xYz2Dg/Onedec-50-1ml.png",
        "Visual-aid": "https://i.ibb.co/chZYCffJ/OH-3-ONEDEC-25-50-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 15,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "VITAMIN-SUPPLEMENTS",
        "Name": "CALDIN ",
        "Composition": "Vitamin B12 50 mcg Calcium Gluconolactobionate 137.5 mg Vitamin D3 5000 I.U. INJECTION",
        "Packing": "5x3ml Ampoule",
        "Mrp": 51.56,
        "Image-link": "https://i.ibb.co/84bDFwhY/Caldin-5-3ml.png",
        "Visual-aid": "https://i.ibb.co/SwFd4yQJ/OH-36-CALDIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 16,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "VITAMIN-SUPPLEMENTS",
        "Name": "COBALDIN + ",
        "Composition": "Methylcobalamin 1000mcg +Nicotinamide 100mg +Pyridoxine HCL 100mg with Dispo Pack INJECTION",
        "Packing": "1x2ml Dispo Pack",
        "Mrp": 72.0,
        "Image-link": "https://i.ibb.co/35wzxxGs/Cobaldin-1-2ml.png",
        "Visual-aid": "https://i.ibb.co/rRjqrvGZ/OH-33-COBALDIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 17,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "VITAMIN-SUPPLEMENTS",
        "Name": "COBALDIN-25 ",
        "Composition": "Methylcobalamin 2500mcg INJECTION",
        "Packing": "1x1ml Dispo Pack       ",
        "Mrp": 56.25,
        "Image-link": "https://i.ibb.co/Q7FV20WQ/Cobaldin-25-1-1ml.png",
        "Visual-aid": null
    },
    {
        "Id": 18,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "VITAMIN-SUPPLEMENTS",
        "Name": "COBALDIN ",
        "Composition": "Methylcobalamin 500mcg INJECTION",
        "Packing": "5x1ml Ampoule",
        "Mrp": 31.0,
        "Image-link": "https://i.ibb.co/VpTgNhK7/Cobaldin-5-1ml.png",
        "Visual-aid": "https://i.ibb.co/rRjqrvGZ/OH-33-COBALDIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 19,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "VITAMIN-SUPPLEMENTS",
        "Name": "COBALDIN FORTE ",
        "Composition": "Methylcobalamin 2500mcg+Folic Acid 0.7mg+Niacinamide 12mg + Vitamin C 150mg  INJECTION",
        "Packing": "2ml Combi Pack ",
        "Mrp": 95.0,
        "Image-link": "https://i.ibb.co/NgFpR6Kv/Cobaldin-Forte.png",
        "Visual-aid": "https://i.ibb.co/xS3v3W5d/OH-34-COBALDIN-FORTE-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 20,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (LIQUID)",
        "Sub-Sub-Category": "VITAMIN-SUPPLEMENTS",
        "Name": "O-D3 ",
        "Composition": "Cholecalciferol IP 60000 I.U./3,00,000 I.U. INJECTION",
        "Packing": "5x1ml Ampoule",
        "Mrp": 60.94,
        "Image-link": "https://i.ibb.co/xqw390BW/OD3-5-1ml.png",
        "Visual-aid": "https://i.ibb.co/Xwm4Vd4/OH-29-OD3-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 21,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ABDOPIME 1000",
        "Composition": "Cefepime 1000mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 194.0,
        "Image-link": "https://i.ibb.co/TxrYyY1v/Abdopime-1000.png",
        "Visual-aid": "https://i.ibb.co/dJkj0bZG/OH-14-ABDOPIME-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 22,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ABDOPIME 250",
        "Composition": "Cefepime 250mg  INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 87.19,
        "Image-link": "https://i.ibb.co/7dP8fRwP/Abdopime-250mg.png",
        "Visual-aid": "https://i.ibb.co/dJkj0bZG/OH-14-ABDOPIME-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 23,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ABDOPIME 500 ",
        "Composition": "Cefepime 500mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 144.38,
        "Image-link": "https://i.ibb.co/4RrXb00X/Abdopime-500.png",
        "Visual-aid": "https://i.ibb.co/dJkj0bZG/OH-14-ABDOPIME-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 24,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ABDOPIME TZ -281.25",
        "Composition": "Cefepime  250mg+Tazobactam 31.25mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 144.38,
        "Image-link": "https://i.ibb.co/VY6TTrnV/Abdopime-TZ-281-25mg.png",
        "Visual-aid": "https://i.ibb.co/4nK1Yc7n/OH-15-ABDOPIME-TZ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 25,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ABDOPIME TZ -562.50",
        "Composition": "Cefepime 500mg+Tazobactam 62.50mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 165.0,
        "Image-link": "https://i.ibb.co/pvWxm9Ch/Abdopime-TZ-562-50mg.png",
        "Visual-aid": "https://i.ibb.co/4nK1Yc7n/OH-15-ABDOPIME-TZ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 26,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN 1000 ",
        "Composition": "Ceftriaxone Sodium1000 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 66.56,
        "Image-link": "https://i.ibb.co/7dS5JxWC/Cefodin-1000mg.png",
        "Visual-aid": "https://i.ibb.co/Q3VthbFL/OH-9-CEFODIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 27,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN 250",
        "Composition": "Ceftriaxone Sodium 250 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 29.76,
        "Image-link": "https://i.ibb.co/HLv0K4Gp/Cefodin-250mg.png",
        "Visual-aid": "https://i.ibb.co/Q3VthbFL/OH-9-CEFODIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 28,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN 500",
        "Composition": "CCeftriaxone Sodium 500 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 52.73,
        "Image-link": "https://i.ibb.co/39NM18Nr/Cefodin-500mg.png",
        "Visual-aid": "https://i.ibb.co/Q3VthbFL/OH-9-CEFODIN-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 29,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN-S 1500 ",
        "Composition": "Ceftriaxone Sodium 1000mg+Sulbactam Sodium 500mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 135.0,
        "Image-link": "https://i.ibb.co/TDYvX6VW/Cefodin-S-1500mg.png",
        "Visual-aid": "https://i.ibb.co/KzjCDbPd/OH-11-CEFODIN-S-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 30,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN-S 375",
        "Composition": "Ceftriaxone Sodium 250mg+Sulbactam Sodium 125mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 56.25,
        "Image-link": "https://i.ibb.co/CKPMQKnS/Cefodin-S-375mg.png",
        "Visual-aid": "https://i.ibb.co/KzjCDbPd/OH-11-CEFODIN-S-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 31,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN-S 750",
        "Composition": "Ceftriaxone Sodium 500mg+Sulbactam Sodium 250mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 128.44,
        "Image-link": "https://i.ibb.co/nGWyth8/Cefodin-S-750mg.png",
        "Visual-aid": "https://i.ibb.co/KzjCDbPd/OH-11-CEFODIN-S-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 32,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN-TZ 1125",
        "Composition": "Ceftriaxone Sodium 1000mg+Tazobactam Sodium 125mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 222.19,
        "Image-link": "https://i.ibb.co/MxXkBdK6/Cefodin-TZ-1125mg.png",
        "Visual-aid": "https://i.ibb.co/3mxQKKYh/OH-10-CEFODIN-TZ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 33,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN-TZ 281.25",
        "Composition": "Ceftriaxone Sodium250mg+Tazobactam Sodium 31.25mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 98.44,
        "Image-link": "https://i.ibb.co/3y2PVhBz/Cefodin-TZ-281-25mg.png",
        "Visual-aid": "https://i.ibb.co/3mxQKKYh/OH-10-CEFODIN-TZ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 34,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFODIN-TZ 562.50",
        "Composition": "Ceftriaxone Sodium 500mg+Tazobactam Sodium 62.50mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 138.75,
        "Image-link": "https://i.ibb.co/kg4qPzQw/Cefodin-TZ-562-5mg.png",
        "Visual-aid": "https://i.ibb.co/3mxQKKYh/OH-10-CEFODIN-TZ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 35,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFTAZIME 1000",
        "Composition": "Ceftazidime 1000mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 238.36,
        "Image-link": "https://i.ibb.co/pr1N9WSZ/Ceftazime-1gm.png",
        "Visual-aid": "https://i.ibb.co/Kxw63p8r/OH-13-CEFTAZIME-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 36,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFTAZIME 250",
        "Composition": "Ceftazidime 250mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 82.97,
        "Image-link": "https://i.ibb.co/ycVww2v1/Ceftazime-250mg.png",
        "Visual-aid": "https://i.ibb.co/Kxw63p8r/OH-13-CEFTAZIME-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 37,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFTAZIME-TZ 1125",
        "Composition": "Ceftazidime 1000 mg + Tazobactam Sodium 125 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 374.0,
        "Image-link": "https://i.ibb.co/j9W7WDkv/Ceftazime-TZ-1125mg.png",
        "Visual-aid": "https://i.ibb.co/PGjTJ0b4/OH-12-CEFTAZIME-TZ-VP-FINAL-28-6-2022.jpg"
    },
    {
        "Id": 38,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFUPAM 1500 ",
        "Composition": "Cefuroxime 1500mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 361.88,
        "Image-link": "https://i.ibb.co/0Rb4XPYS/Cefupam-1500mg.png",
        "Visual-aid": "https://i.ibb.co/prn70k3N/OH-18-CEFUPAM-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 39,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "CEFUPAM 250",
        "Composition": "Cefuroxime 250mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 103.13,
        "Image-link": "https://i.ibb.co/9HjR6vsc/Cefupam-250mg.png",
        "Visual-aid": "https://i.ibb.co/prn70k3N/OH-18-CEFUPAM-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 40,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "INTRONEM 1000",
        "Composition": "Meropenem 1000mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 1017.65,
        "Image-link": "https://i.ibb.co/ZpFkvbjx/Intronem-1gm.png",
        "Visual-aid": "https://i.ibb.co/KjzVMFsW/OH-4-INTRONEM-1-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 41,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ODIZONE-S 1500",
        "Composition": "Cefoperazone Sodium 1000mg + Sulbactam Sodium 500 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 234.38,
        "Image-link": "https://i.ibb.co/PGVHNpPz/Odizone-S-1-5gm.png",
        "Visual-aid": "https://i.ibb.co/wZWHMhf1/OH-7-ODIZONE-S-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 42,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "ODIZONE-S 1000 ",
        "Composition": "Cefoperazone Sodium 500mg + Sulbactam Sodium 500mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 186.56,
        "Image-link": "https://i.ibb.co/cSCqcq1w/Odizone-S-1gm.png",
        "Visual-aid": "https://i.ibb.co/wZWHMhf1/OH-7-ODIZONE-S-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 43,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "ANTI-BACTERIAL",
        "Name": "PIPDIN-TZ 4500 ",
        "Composition": "Piperacillin Sodium 4000mg + Tazobactam Sodium 500 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 426.56,
        "Image-link": "https://i.ibb.co/4n86dV0h/Pipdin-TZ-4-5gm.png",
        "Visual-aid": "https://i.ibb.co/WpVp99dV/OH-6-PIPDIN-TZ-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 44,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "PANTODIN-40",
        "Composition": "Pantoprazole Sodium 40mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 53.9,
        "Image-link": "https://i.ibb.co/Cshwdxv6/Pantodin-40mg.png",
        "Visual-aid": "https://i.ibb.co/wFgb54S3/OH-20-PANTODIN-40-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 45,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "ROSCOBATE ",
        "Composition": "Esomeprazole Sodium 40mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 147.19,
        "Image-link": "https://i.ibb.co/XmchRxq/Roscobate-40mg.png",
        "Visual-aid": "https://i.ibb.co/qYcLhhPk/OH-21-ROSCOBATE-40-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 46,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "H-CORT 100",
        "Composition": "Hydrocortisone Sodium Succinate 100mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 47.0,
        "Image-link": "https://i.ibb.co/fVP59mFY/H-Cort-100mg.png",
        "Visual-aid": "https://i.ibb.co/pvPwyH6m/OH-22-H-CORT-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 47,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "H-CORT 200",
        "Composition": "Hydrocortisone Sodium Succinate 200mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 68.88,
        "Image-link": "https://i.ibb.co/NgB8pzwN/H-Cort-200mg.png",
        "Visual-aid": "https://i.ibb.co/pvPwyH6m/OH-22-H-CORT-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 48,
        "Category": "INJECTIONS",
        "Sub-category": "INJECTIONS (DRY)",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "PREDIN-40",
        "Composition": "Methyl Prednisolone Sodium Succinate 40 mg INJECTION",
        "Packing": "Vial Pack ",
        "Mrp": 53.9,
        "Image-link": "https://i.ibb.co/rGmd6QHc/Predin-40mg.png",
        "Visual-aid": "https://i.ibb.co/8kvLkpT/OH-23-PREDIN-40-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 49,
        "Category": "DROPS",
        "Sub-category": "Ear Drop ",
        "Sub-Sub-Category": "EAR DROPS ANTI FUNGAL/ANTI BECTERIA ",
        "Name": "CHLOCIN-B ",
        "Composition": "Chloramphenicol 5%w/v+Beclomethasone Dipropionate 0.025w/v+Clotrimazole 1%w/v+Glycerin 2%v/v EAR DROPS",
        "Packing": "10ml Vial ",
        "Mrp": 82.5,
        "Image-link": "https://i.ibb.co/zVMPydPx/Chlocin-B-10ml.png",
        "Visual-aid": "https://i.ibb.co/sp7qd7Jr/OH-37-CHLOCIN-B-EAR-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 50,
        "Category": "DROPS",
        "Sub-category": "Ear Drop ",
        "Sub-Sub-Category": "EAR DROPS ANTI FUNGAL/ANTI BECTERIA ",
        "Name": "ODIWAX ",
        "Composition": "Paradichlorobenzene  2.0%w/v+Benzocaine2.7%w/v + Chlorbutol 5%w/v+Turpentine Oil 15% w/v EAR DROPS",
        "Packing": "10ml Vial ",
        "Mrp": 107.0,
        "Image-link": "https://i.ibb.co/5qsXYxv/Odiwax-10ml.png",
        "Visual-aid": "https://i.ibb.co/N6dD0ycy/OH-51-ODIWAX-EAR-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 51,
        "Category": "DROPS",
        "Sub-category": "Ear Drop ",
        "Sub-Sub-Category": "EAR DROPS ANTI FUNGAL/ANTI BECTERIA ",
        "Name": "OPTICIN-CL",
        "Composition": "Clotrimazole 1%w/v+Lignocaine Hydrochloride  2%W/V EAR DROPS",
        "Packing": "10ml Vial",
        "Mrp": 87.19,
        "Image-link": "https://i.ibb.co/KpmNW1XK/Opticin-CL-10ml.png",
        "Visual-aid": "https://i.ibb.co/nsB3CKK2/OH-59-OPTICIN-CL-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 52,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "SOOTHIG-AGENT",
        "Name": "EYECARE GEL ",
        "Composition": "Carboxy Methyl Cellulose Sodium 1% w/v + Stabilized Oxychloro Complex 0.005%w/v GEL ",
        "Packing": "10ml Vial ",
        "Mrp": 177.0,
        "Image-link": "https://i.ibb.co/B56ghyWt/Eye-Care-Gel-10ml.png",
        "Visual-aid": "https://i.ibb.co/q3ZyT3fs/OH-39-EYE-CAR-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 53,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "SOOTHIG-AGENT",
        "Name": "EYE-NAC ",
        "Composition": "Carboxy MethylCellulose 0.3%w/v + N- Acetylcarnosine 1%w/v + Glycerine 1% w/v + Boric Acid 0.1% w/v + Benzyl Alcohol 0.1% v/v EYE DROPS ",
        "Packing": "10ml Vial ",
        "Mrp": 192.19,
        "Image-link": "https://i.ibb.co/5X8cFfqL/Eye-Nac-10ml.png",
        "Visual-aid": "https://i.ibb.co/wNNrJkYV/OH-41-EYE-NAC-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 54,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "SOOTHIG-AGENT",
        "Name": "EYECARE ",
        "Composition": "Carboxy Methyl Cellulose Sodium 0.5% w/v + Stabilized Oxychloro Complex 0.005% w/v Drops ",
        "Packing": "10ml Vial ",
        "Mrp": 131.0,
        "Image-link": "https://i.ibb.co/5X8cFfqL/Eye-Nac-10ml.png",
        "Visual-aid": "https://i.ibb.co/q3ZyT3fs/OH-39-EYE-CAR-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 55,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "SOOTHIG-AGENT",
        "Name": "EYE CARE-400",
        "Composition": "Polyethylene Glycol 0.4%w/v+Propylene Glycol 0.3%w/v EYE DROPS ",
        "Packing": "10ml Vial ",
        "Mrp": 268.0,
        "Image-link": "https://i.ibb.co/Y75YxxC9/Eye-Care-400-10ml.png",
        "Visual-aid": "https://i.ibb.co/8DWBFmFL/OH-40-EYE-CAR-400-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 56,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "GETFLO ",
        "Composition": "Gatifloxacin 0.3%w/v + Benzalkonium Chloride Solution 0.01%v/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 51.56,
        "Image-link": "https://i.ibb.co/PvZwPw4r/Getflo-5ml.png",
        "Visual-aid": "https://i.ibb.co/fYZFZpW3/OH-43-GETFLO-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 57,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "SOOTHIG-AGENT",
        "Name": "HYLODIN ",
        "Composition": "Sodium Hyaluronate BP 0.1% w/v + Sodium Perbonate BP 0.028% w/v EYE DROPS ",
        "Packing": "10ml Vial ",
        "Mrp": 396.56,
        "Image-link": "https://i.ibb.co/tPDj52nQ/Hylodin-10ml.png",
        "Visual-aid": "https://i.ibb.co/bMJn0bjf/OH-45-HYLODIN-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 58,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "KI-O ",
        "Composition": "Ketorolac Tromethamine  0.5%w/v +Ofloxacin 0.3%w/v+Benzalkonium Chloride Solution 0.01%v/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 72.19,
        "Image-link": "https://i.ibb.co/DPFMwQbc/KI-O-5ml.png",
        "Visual-aid": "https://i.ibb.co/Kjz0v5hz/OH-46-KI-O-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 59,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-ALLERGIC",
        "Name": "KI-OL ",
        "Composition": "Olopatadine Hydrochloride 0.1% w/v+ ketorolac Tromethamine 0.4% w/v + Benzalkonium Chloride Solution 0.01%v/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 97.5,
        "Image-link": "https://i.ibb.co/gZQxr1Gh/KI-OL-5ml.png",
        "Visual-aid": "https://i.ibb.co/HLDm2j8N/OH-47-KI-OL-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 60,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "SOOTHIG-AGENT",
        "Name": "NHC ",
        "Composition": "Naphazoline Hydrochloride 0.05%w/v +Carboxymethylcellulose Sodium 0.2%w/v/+Chlorpheniramine Maleate 0.01%w/v+Camphor 0.01%w/v+Stabilized Oxycholoro Complex 0.005%w/v EYE DROPS ",
        "Packing": "10ml Vial ",
        "Mrp": 89.0,
        "Image-link": "https://i.ibb.co/7tvt3JWC/NHC-10ml.png",
        "Visual-aid": "https://i.ibb.co/MQKmzWN/OH-48-NHC-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 61,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "EAR DROPS ANTI FUNGAL/ANTI BECTERIA ",
        "Name": "ODIMOX ",
        "Composition": "Moxifloxacin Hydrochloride 0.5%w/w EYE OINTMENT ",
        "Packing": "5gm Tube ",
        "Mrp": 79.69,
        "Image-link": "https://i.ibb.co/gZNsd7N4/Odimox-5gm.png",
        "Visual-aid": "https://i.ibb.co/GvMXdWw0/OH-68-ODIMOX-EYE-OINT-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 62,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "ODIMOX-BN",
        "Composition": "Moxifloxacin Hydrochloride0.5%w/v + Bromfenac Sodium 0.09%w/v+Benzalkonium Chloride Solution 0.01%v/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 113.44,
        "Image-link": "https://i.ibb.co/vC5DvG0X/Odimox-BN-5ml.png",
        "Visual-aid": "https://i.ibb.co/ZzZ4cBgK/OH-55-ODIMOX-BN-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 63,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "Odimox-DX",
        "Composition": "Moxifloxacin Hydrochloride 0.5%w/v + Dexamethasone Sodium Phosphate 0.1%w/v+Stabilized Oxycholoro Complex 0.005%w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 112.5,
        "Image-link": "https://i.ibb.co/zhzTmqwJ/Odimox-DX-5ml.png",
        "Visual-aid": "https://i.ibb.co/4LSTvbG/oh-340-ODIMOX-DX-VP-9-1-2024.jpg"
    },
    {
        "Id": 64,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "ODIMOX-LT ",
        "Composition": "Moxifloxacin Hydrochloride0.5%w/v + Lotepredinol Etabonate 0.5%w/v+Stabilized Oxycholoro Complex 0.005%w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 169.69,
        "Image-link": "https://i.ibb.co/Ld0tJyhw/Odimox-LT-5ml.png",
        "Visual-aid": "https://i.ibb.co/Zp6SYbbH/OH-56-ODIMOX-LT-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 65,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-INFLAMMATORY & ANALGESIC",
        "Name": "OFEN ",
        "Composition": "Flurbiprofen Sodium 0.03%w/v+Phenylmercuric Nitrate 0.002%w/v+HPMC 0.025w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 61.88,
        "Image-link": "https://i.ibb.co/7hSSQjN/Ofen-5ml.png",
        "Visual-aid": "https://i.ibb.co/1kZGnbB/OH-57-OFEN-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 66,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-ALLERGIC",
        "Name": "OLLINE ",
        "Composition": "Olopatadine 0.1% w/v+Stabilized Oxycholoro Complex 0.005%w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 120.94,
        "Image-link": "https://i.ibb.co/k2wgPD1P/Olline-5ml.png",
        "Visual-aid": "https://i.ibb.co/Df9YkmB7/OH-61-OLLINE-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 67,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-INFLAMMATORY & ANALGESIC",
        "Name": "ONEP ",
        "Composition": "Nepafenac 0.1%W/V+Benzalkonium Chloride Solution 0.01%v/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 128.44,
        "Image-link": "https://i.ibb.co/H0WVcGQ/Onep-5ml.png",
        "Visual-aid": "https://i.ibb.co/CKkdMtMJ/OH-63-ONEP-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 68,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "OPTICIN ",
        "Composition": "Ofloxacin 0.3%w/v+ Benzalkonium Chloride Solution 0.01%v/v EYE DROPS",
        "Packing": "5ml Vial ",
        "Mrp": 30.94,
        "Image-link": "https://i.ibb.co/DftHRWxP/Opticin-5ml.png",
        "Visual-aid": "https://i.ibb.co/MkcnCgyM/OH-58-OPTICIN-EYE-DROP-VP-FINAL-16-5-2022.jpg"
    },
    {
        "Id": 69,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-CATARACT",
        "Name": "TASSM-CAT ",
        "Composition": "Potssium Iodide 3.3% w/v +  Calcium Chloride 1%w/v +Sodium Chlode 0.83%w/v + Methyl Paraben 0.023%w/v Propyl Paraben 0.011%w/v EYE DROPS ",
        "Packing": "10ml Vial ",
        "Mrp": 51.56,
        "Image-link": "https://i.ibb.co/TxVh6n8K/Tassm-Cat-10ml.png",
        "Visual-aid": "https://i.ibb.co/8DD9RwZ7/OH-64-TASSM-CAT-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 70,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-GLAUCOMA",
        "Name": "TIMODIN ",
        "Composition": "Timolol Maleate 0.5% + Benzalkonium Chloride Solution 0.01%w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 70.29,
        "Image-link": "https://i.ibb.co/B2prpXSt/Timodin-5ml.png",
        "Visual-aid": "https://i.ibb.co/27QFS1GX/OH-67-TIMODIN-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 71,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "TOBRADIN ",
        "Composition": "Tobramycin Sulphate 0.3%w/v+ Benzalkonium Chloride Solution 0.01%v/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 70.0,
        "Image-link": "https://i.ibb.co/9ksV0JDX/Tobradin-5ml.png",
        "Visual-aid": "https://i.ibb.co/mLPFLgX/OH-65-TOBRADIN-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 72,
        "Category": "DROPS",
        "Sub-category": "Eye Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "TOBRADIN-F ",
        "Composition": "Tobramycin Sulphate 0.3%w/v +Fluorometholone 0.1%w/v+Stabilized Oxycholoro Complex 0.005%w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 97.5,
        "Image-link": "https://i.ibb.co/1fVgv6fR/Tobradin-F-5ml.png",
        "Visual-aid": "https://i.ibb.co/dszMdD2x/OH-66-TOBRADIN-F-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 73,
        "Category": "DROPS",
        "Sub-category": "Eye Drop/Ear Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "OPTICIN-D ",
        "Composition": "Ofloxacin 0.3%w/v+ Betamethasone Sodium Phosphate 0.1%w/v + Benzalkonium Chloride Solution 0.01%v/v EYE/EAR DROPS",
        "Packing": "5ml Vial ",
        "Mrp": 35.63,
        "Image-link": "https://i.ibb.co/gM8DXLFb/Opticin-D-5ml.png",
        "Visual-aid": "https://i.ibb.co/GvGv1Jwt/OH-60-OPTICIN-D-EYE-DROP-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 74,
        "Category": "DROPS",
        "Sub-category": "Eye Drop/Ear Drop",
        "Sub-Sub-Category": "ANTI-BIOTICS COMBINATIONS",
        "Name": "OTICIN-D",
        "Composition": "Ofloxacin 0.3%w/v+ Betamethasone Sodium Phosphate 0.1%w/v + Benzalkonium Chloride Solution 0.01%v/v EYE/EAR DROPS",
        "Packing": "5ml Vial ",
        "Mrp": 35.63,
        "Image-link": "https://i.ibb.co/844GjHk4/Oticin-D-5ml.png",
        "Visual-aid": null
    },
    {
        "Id": 75,
        "Category": "DROPS",
        "Sub-category": "Eye Ointment",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "ODIMOX ",
        "Composition": "Moxifloxacin Hydrochloride 0.5%w/v EYE DROPS ",
        "Packing": "5ml Vial ",
        "Mrp": 112.5,
        "Image-link": "https://i.ibb.co/TqKgRSRn/Odimox-5ml.png",
        "Visual-aid": "https://i.ibb.co/0j6xDbJ1/OH-52-ODIMOX-EYE-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 76,
        "Category": "DROPS",
        "Sub-category": "Nasal Drop ",
        "Sub-Sub-Category": "NASAL CONGESTION & INFECTION",
        "Name": "NOSUM",
        "Composition": "Sodium Chloride 0.65% + Benzalkonium Chloride Solution 0.01%v/v  NASAL DOPS",
        "Packing": "15ml Vial ",
        "Mrp": 56.0,
        "Image-link": "https://i.ibb.co/ycCxt4Cr/Nosum-15ml.png",
        "Visual-aid": "https://i.ibb.co/mCtQQVqH/OH-50-NOSUM-NASAL-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 77,
        "Category": "Sprays",
        "Sub-category": "Nasal",
        "Sub-Sub-Category": "NASAL CONGESTION & INFECTION",
        "Name": "MOTIN",
        "Composition": "Mometasone Furoate 0.1% W/W CREAM ",
        "Packing": "20gm Tube ",
        "Mrp": 97.5,
        "Image-link": "https://i.ibb.co/6RX1p5KX/Motin-10ml.png",
        "Visual-aid": "https://i.ibb.co/PzFK0K4M/OH-71-MOTIN-NASAL-SPRAY-VP-FINAL-16-62022.jpg"
    },
    {
        "Id": 78,
        "Category": "Sprays",
        "Sub-category": "Nasal",
        "Sub-Sub-Category": "NASAL CONGESTION & INFECTION",
        "Name": "NOVIN",
        "Composition": "Xylometazoline Hydrochloride 0.1% w/v  NASAL DOPS/ SPRAY ",
        "Packing": "10ml Vial ",
        "Mrp": 53.76,
        "Image-link": "https://i.ibb.co/ccP5QwVY/Novin-10ml.png",
        "Visual-aid": "https://i.ibb.co/dJG6wsN2/OH-51-NOVIN-NASAL-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 79,
        "Category": "Sprays",
        "Sub-category": "Nasal",
        "Sub-Sub-Category": "NASAL CONGESTION & INFECTION",
        "Name": "NOVIN KID ",
        "Composition": "Xylometazoline Hydrochloride 0.05%w/v NASAL DOPS/ SPRAY ",
        "Packing": "10ml Vial ",
        "Mrp": 43.99,
        "Image-link": "https://i.ibb.co/cqVVB3p/Novin-kid-10ml.png",
        "Visual-aid": "https://i.ibb.co/dJG6wsN2/OH-51-NOVIN-NASAL-DROP-VP-FINAL-15-6-2022.jpg"
    },
    {
        "Id": 80,
        "Category": "Sprays",
        "Sub-category": "Nasal",
        "Sub-Sub-Category": "NASAL CONGESTION & INFECTION",
        "Name": "OFLUTE ",
        "Composition": "Fluticasone Propionate 0.05% w/v+Benzalkonium Chloride Solution 0.01%v/v+Phenyl Ethyl Alcohol  0.25% v/v NASAL SPRAY ",
        "Packing": "10ml Vial ",
        "Mrp": 398.44,
        "Image-link": "https://i.ibb.co/Mk0pFq0k/Oflute-10ml.png",
        "Visual-aid": "https://i.ibb.co/RTgfFbm1/OH-77-OFLUTE-NASAL-SPRAY-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 81,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "CALCIUM SUPPLEMENTS",
        "Name": "CALDIN-XT ",
        "Composition": "Calcium Carbonate 1250mg+Vitamin D3 2000IU+Methylcobalamin 1500mcg+L-Methylfolate Calcium 1mg+Pyridoxal 5- Phosphate 20mg TABLETS",
        "Packing": "10x15 Blister",
        "Mrp": 3375.0,
        "Image-link": "https://i.ibb.co/xSyZTTqL/Caldin-xt-10x15.png",
        "Visual-aid": "https://i.ibb.co/4w5cYLJF/OH-163-CALDIN-XT-VP-FINAL-16-10-2023.jpg"
    },
    {
        "Id": 82,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "CEKLO AS ",
        "Composition": "Aceclofenac 100 mg + Serratiopeptidase 15 mg TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 876.0,
        "Image-link": "https://i.ibb.co/qL99y6Z3/Ceklo-AS-10x10.png",
        "Visual-aid": "https://i.ibb.co/nNs0NjXC/OH-97-CEKLO-AS-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 83,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "CEKLO MR ",
        "Composition": "Aceclofenac 100mg +Paracetamol 325mg+Chlorzoxazone 250mg TABLETS ",
        "Packing": "10x10 Blister ",
        "Mrp": 665.0,
        "Image-link": "https://i.ibb.co/dsm00hrK/Ceklo-mr-10x10.png",
        "Visual-aid": "https://i.ibb.co/j9qdGqSq/OH-99-CEKLO-MR-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 84,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "CEKLO-P",
        "Composition": "Aceclofenac 100 mg Paracetamol 325 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 431.0,
        "Image-link": "https://i.ibb.co/6JTBkZrH/Ceklo-p-10x10.png",
        "Visual-aid": "https://i.ibb.co/0yNBGtvW/OH-100-CEKLO-P-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 85,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "CEKLO PS ",
        "Composition": "Aceclofenac 100 mg + Paracetamol 325 mg+ Serratiopeptidase 15 mg TABLETS\n",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1021.5,
        "Image-link": "https://i.ibb.co/rfM8P00W/Ceklo-ps-10x10.png",
        "Visual-aid": "https://i.ibb.co/ynjd05h0/OH-99-CEKLO-PS-FINAL-23-6-2022.jpg"
    },
    {
        "Id": 86,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "CEKLO-TH 4",
        "Composition": "Aceclofenac 100mg+Paracetamol 325 +Thiocolchicoside 4mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 2700.0,
        "Image-link": "https://i.ibb.co/SwVcrDVr/Ceklo-th4-10x10.png",
        "Visual-aid": "https://i.ibb.co/chYkc1zg/OH-166-CEKLO-TH4-VP-FINAL-16-10-2023.jpg"
    },
    {
        "Id": 87,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NOOTROPIC",
        "Name": "COBALDIN ",
        "Composition": "Folic Acid 5mg+Pyridoxine Hydrochloride 10mg+ Methylcobalamin 1500mcg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1265.0,
        "Image-link": "https://i.ibb.co/MDzYyQhR/Cobaldin-10x10.png",
        "Visual-aid": "https://i.ibb.co/0ywM3XMX/OH-161-COBALDIN-TABS-VP-21-4-2023.jpg"
    },
    {
        "Id": 88,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "DILON-P ",
        "Composition": "Diclofenac Potassium 50mg+Paracetamol  325mg TABLETS ",
        "Packing": "10x10 Blister ",
        "Mrp": 393.0,
        "Image-link": "https://i.ibb.co/C55Byk7y/Dilon-P-10x10.png",
        "Visual-aid": "https://i.ibb.co/vCtrLHdP/OH-164-DILON-P-VP-FINAL-16-10-2023.jpg"
    },
    {
        "Id": 89,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "DILON-S ",
        "Composition": "Diclofenac Potassium 50 mg + Serratiopeptidase 10 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 843.0,
        "Image-link": "https://i.ibb.co/9kZQtXxj/Dilon-S-10x10.png",
        "Visual-aid": "https://i.ibb.co/B5SHQHfy/OH-104-DILON-S-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 90,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PREGnullCY",
        "Name": "DOCID ",
        "Composition": "Doxylamine 10 mg +Pyridoxine HCL10 mg +Folic Acid 5 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 571.88,
        "Image-link": "https://i.ibb.co/BVbzZJ1V/Docid-10x10.png",
        "Visual-aid": null
    },
    {
        "Id": 91,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "BRONCHODILATORS",
        "Name": "DOPHIN ",
        "Composition": "Doxofylline 400mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1406.0,
        "Image-link": "https://i.ibb.co/23fH6G5H/Dophin-10x10.png",
        "Visual-aid": "https://i.ibb.co/B5B2rLDz/OH-344-DOPHIN-VP-27-5-2024.jpg"
    },
    {
        "Id": 92,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "EFI 200 LB TAB.",
        "Composition": "Cefixime Trihydrate200mg + Lactic Acid Bacillus 60 million spores TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1500.0,
        "Image-link": "https://i.ibb.co/0y4jcWwt/EFI-200-LB-10x10.png",
        "Visual-aid": "https://i.ibb.co/Q35Qxwt2/OH-348-EFI-200-LB-TAB-VP-17-2-2025-NEW.jpg"
    },
    {
        "Id": 93,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "EFI-CL ",
        "Composition": "Cefixime 200 mg + Potassium Clavulanate 125 mg TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 3609.38,
        "Image-link": "https://i.ibb.co/SXFFc3rK/EFI-CL-10x10.png",
        "Visual-aid": "https://i.ibb.co/d0Bb6rjM/OH-105-EFI-CL-VP-FINAL-24-6-2022.jpg"
    },
    {
        "Id": 94,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "EFI-O ",
        "Composition": "Cefixime Trihydrate 200 mg + Ofloxacin 200 mg TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1500.0,
        "Image-link": "https://i.ibb.co/7JsWYJHs/EFI-O-10x10.png",
        "Visual-aid": "https://i.ibb.co/zhb9g33h/OH-109-EFI-O-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 95,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "ESTRODIN ",
        "Composition": "Itopride HCl 50 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 567.3,
        "Image-link": "https://i.ibb.co/kVRnw1LV/Estrodin-10x10.png",
        "Visual-aid": "https://i.ibb.co/NdWmf486/OH-106-ESTRODIN-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 96,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "ETODIN ",
        "Composition": "Etoricoxib 90 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 928.0,
        "Image-link": "https://i.ibb.co/tMWDNktM/Etodin-10x10.png",
        "Visual-aid": "https://i.ibb.co/CKVpS9c4/OH-110-ETODIN-VP-FINAL-16-6-2021.jpg"
    },
    {
        "Id": 97,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "ETODIN-P ",
        "Composition": "Etoricoxib 60 mg + Paracetamol 325 mg TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 975.0,
        "Image-link": "https://i.ibb.co/zVFxxWmr/Etodin-p-10x10.png",
        "Visual-aid": "https://i.ibb.co/q3N26NRh/OH-111-ETODIN-P-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 98,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "HAEMATINICS",
        "Name": "FEROROFER-FM ",
        "Composition": "Ferrous Bisglycinate 60mg+ Zinc Bisglycinate15mg+Folic Acid 1mg +Methylcobalamin 500mcg TABLETS\n",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1734.0,
        "Image-link": "https://i.ibb.co/XfDQMmBJ/Ferorofer-Fm-10x10.png",
        "Visual-aid": "https://i.ibb.co/nN5xbVcg/OH-158-FEROROFER-FM-VP-13-10-2022.jpg"
    },
    {
        "Id": 99,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "HAEMATINICS",
        "Name": "FEROROFER-XT ",
        "Composition": "Ferrous Ascorbate 100 mg +Folic Acid 1.5 mg +Zinc Selphate 22.5mgTABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 918.0,
        "Image-link": "https://i.ibb.co/70MXb3Q/Ferorofer-Xt-10x10.png",
        "Visual-aid": "https://i.ibb.co/SXPkzxh2/OH-112-FEROROFER-XT-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 100,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "FPOXIL-200 DT ",
        "Composition": "Cefpodoxime Proxetil 200mg TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 2578.0,
        "Image-link": "https://i.ibb.co/JWxGP0Rt/Fpoxil-200-DT-10x10.png",
        "Visual-aid": "https://i.ibb.co/MDFFDHWF/OH-113-FPOXIL-CL-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 101,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "FPOXIL-CL ",
        "Composition": "Cefpodoxime 200mg + Potassium Clavulanate 125 mg TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 3628.0,
        "Image-link": "https://i.ibb.co/LzNypksq/Fpoxil-cl-10x10.png",
        "Visual-aid": "https://i.ibb.co/MDFFDHWF/OH-113-FPOXIL-CL-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 102,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NOOTROPIC",
        "Name": "GAB-NT ",
        "Composition": "Gabapentin 400mg + Nortriptyline Hydrochloride 10mg  TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 2250.0,
        "Image-link": "https://i.ibb.co/S7BR734f/Gab-Nt-10x10.png",
        "Visual-aid": "https://i.ibb.co/qLrjb3Fg/OH-167-GAB-NT-VP-FINAL-16-10-2023.jpg"
    },
    {
        "Id": 103,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "HAEMATINICS",
        "Name": "I RICH ",
        "Composition": "Ferrous Ascorbate 100mg+Folic Acid 1.5mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1265.0,
        "Image-link": "https://i.ibb.co/k2NZszRf/I-rich-10x10.png",
        "Visual-aid": "https://i.ibb.co/4g7TsB9t/OH-343-I-RICH-VP-24-5-2024.jpg"
    },
    {
        "Id": 104,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "INTROFEM 200 ",
        "Composition": "Faropenem Sodium 200mg TABLETS ",
        "Packing": "10x1x10 Alu Alu",
        "Mrp": 9281.0,
        "Image-link": "https://i.ibb.co/vvKLXjCL/Introfem-200-1x10.png",
        "Visual-aid": "https://i.ibb.co/3HwYqPy/OH-351-INTROFEM-200-TAB-VP-17-2-2025-NEW.jpg"
    },
    {
        "Id": 105,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PREGnullCY",
        "Name": "ISODIN-SR ",
        "Composition": "Isoxsuprine HCL 40 mg SR TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 684.4,
        "Image-link": "https://i.ibb.co/twvctjzS/Isodin-sr-10x10.png",
        "Visual-aid": "https://i.ibb.co/Y7PcPJ6S/OH-114-ISODIN-SR-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 106,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-COLD",
        "Name": "LERNIX ",
        "Composition": "Levocetirizine Dihydrochloride 5 mg + Ambroxol HCl 75 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 562.5,
        "Image-link": "https://i.ibb.co/1YBN4nxk/Lernix-10x10.png",
        "Visual-aid": "https://i.ibb.co/bgxP3y4V/OH-115-LERNIX-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 107,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-ALLERGIC/ANTI ASTHMATICS",
        "Name": "MONTEBIL ",
        "Composition": "Montelukast Sodium 10mg+Bilastine 20mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1687.5,
        "Image-link": "https://i.ibb.co/LzFTXSHp/Montebil-10x10.png",
        "Visual-aid": "https://i.ibb.co/0pFHz4vN/OH-355-MONTEBIL-VP-9-11-2024-NEW.jpg"
    },
    {
        "Id": 108,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-ALLERGIC/ANTI ASTHMATICS",
        "Name": "MONTEDIN ",
        "Composition": "Montelukast Sodium 10 mg + Levocetirizine Dihydrochloride 5 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1021.0,
        "Image-link": "https://i.ibb.co/S4tC9Ks2/Montedin-10x10.png",
        "Visual-aid": "https://i.ibb.co/4ngW4vvg/OH-113-MONTEDIN-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 109,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-FIBRINOLYTIC",
        "Name": "NEXIC-M ",
        "Composition": "Tranexamic Acid 500 mg + Mefenamic Acid 250 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 2559.0,
        "Image-link": "https://i.ibb.co/q3pk7Z8q/Nexic-M-10x10.png",
        "Visual-aid": "https://i.ibb.co/k6z6ghQz/OH-118-NEXIC-M-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 110,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-EMETIC",
        "Name": "ODESTRON-4 ",
        "Composition": "Ondansetron HCI 4 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 538.59,
        "Image-link": "https://i.ibb.co/LDDTj03P/Odestron-4-10x10.png",
        "Visual-aid": "https://i.ibb.co/RkrPxdSv/OH-132-ODESTRON-4-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 111,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "CALCIUM SUPPLEMENTS",
        "Name": "ODICAL ",
        "Composition": "Calcium Carbonate 1250 mg + Vitamin D3 250 IU+Calcium 500mg  TABLETS",
        "Packing": "10x15 Blister",
        "Mrp": 890.63,
        "Image-link": "https://i.ibb.co/V7WXsrp/Odical-10x15.png",
        "Visual-aid": "https://i.ibb.co/d4DXYJhf/OH-133-ODICAL-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 112,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "ODICLAV-625",
        "Composition": "Amoxycillin Trihydrate 500 mg + Potassium Clavulanate 125mg TABLETS ",
        "Packing": "5x10 Alu Alu",
        "Mrp": 915.94,
        "Image-link": "https://i.ibb.co/pvkRWSzc/Odiclav-625-5x10.png",
        "Visual-aid": "https://i.ibb.co/0jzHZthJ/OH-121-ODICLAV-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 113,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "ODICLAV-625 LB",
        "Composition": "Amoxycillin Trihydrate 500 mg + Potassium Clavulanate 125mg+ Lactic Acid Bacillus 60 million spores TABLETS ",
        "Packing": "10X1x6 Alu Alu",
        "Mrp": 1050.0,
        "Image-link": "https://i.ibb.co/gMs7Z6MX/Odiclav-625-LB-10x1x6.png",
        "Visual-aid": "https://i.ibb.co/hTJ4Rc7/OH-360-ODICLAV-LB-625-VP-28-5-2025-NEW.jpg"
    },
    {
        "Id": 114,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-COLD",
        "Name": "ODIKOLD ",
        "Composition": "Paracetamol  500mg+Phenylephrine Hydrochloride5mg+Caffeine 30mg+Diphenhydramine Hydrochloride 25mg TABLETS",
        "Packing": "10x10 Blister ",
        "Mrp": 609.0,
        "Image-link": "https://i.ibb.co/7xwHWQZc/Odikold-10x10.png",
        "Visual-aid": "https://i.ibb.co/XZ9Hyt7N/OH-165-ODIKOLD-VP-FINAL-16-10-2023.jpg"
    },
    {
        "Id": 115,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-ALLERGIC/ANTI ASTHMATICS",
        "Name": "ODILEV",
        "Composition": "Levocetirizine HCI 5 mg TABLETS",
        "Packing": "5x5x10 Blister ",
        "Mrp": 721.88,
        "Image-link": "https://i.ibb.co/BVjVmQVW/Odilev-10x10.png",
        "Visual-aid": "https://i.ibb.co/VpJfjmrr/OH-125-ODILEV-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 116,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI SPASMODIC",
        "Name": "ODISPAS-AC ",
        "Composition": "Drotaverine HCL 80 mg Aceclofenac 100 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 937.5,
        "Image-link": "https://i.ibb.co/pv3hyWGf/Odispas-AC-10x10.png",
        "Visual-aid": "https://i.ibb.co/twPFjDSn/OH-123-ODISPAS-AC-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 117,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI SPASMODIC",
        "Name": "ODISPAS-M ",
        "Composition": "Drotaverine HCI 80 mg Mefenamic Acid 250 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 712.5,
        "Image-link": "https://i.ibb.co/1GjNDXx3/Odispas-M-10x10.png",
        "Visual-aid": "https://i.ibb.co/8L0whz0N/OH-122-ODISPAS-M-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 118,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-COLD",
        "Name": "ODIX ",
        "Composition": "Aceclofenac 100mg +Paracetamol 325mg+Cetirizine Hydrochloride 10mg+Phenylephrine  Hydrochloride 5mg+Caffeine 25mg TABLETS",
        "Packing": "10x10 Blister ",
        "Mrp": 890.0,
        "Image-link": "https://i.ibb.co/Jw8PyvtM/Odix-10x10.png",
        "Visual-aid": "https://i.ibb.co/Jjpd9Lyx/OH-345-ODIX-VP-27-5-2024.jpg"
    },
    {
        "Id": 119,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "ODOZITH-250 ",
        "Composition": "Azithromycin Dihydrate 250 mg INJECTION",
        "Packing": "Blister Pack ",
        "Mrp": 0.0,
        "Image-link": "https://i.ibb.co/zWcFMGRJ/Odozith-250-10x6.png",
        "Visual-aid": "https://i.ibb.co/23jgvSq9/OH-120-ODOZITH-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 120,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "ODOZITH-500 ",
        "Composition": "Azithromycin Dihydrate 500 mg INJECTION",
        "Packing": "10X5 Blister Pack ",
        "Mrp": 1237.5,
        "Image-link": "https://i.ibb.co/Qjqbv4Jv/Odozith-500-10x5.png",
        "Visual-aid": "https://i.ibb.co/23jgvSq9/OH-120-ODOZITH-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 121,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "ODOZITH-500 LB",
        "Composition": "Azithromycin Dihydrate 500 mg+Lactic Acid Bacillus 60 million spores TABLETS ",
        "Packing": "10x5 Blister",
        "Mrp": 1312.5,
        "Image-link": "https://i.ibb.co/C3JTRk9V/Odozith-Lb-500-10x5.png",
        "Visual-aid": null
    },
    {
        "Id": 122,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "OFDIN ",
        "Composition": "Ofloxacin 200 mg TABLETS ",
        "Packing": "5x5x10 Blister",
        "Mrp": 1359.38,
        "Image-link": "https://i.ibb.co/Df5B23RB/Ofdin-5x5x10.png",
        "Visual-aid": "https://i.ibb.co/HDL8yvRM/OH-126-OFDIN-OZ-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 123,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-BIOTICS",
        "Name": "OFDIN-OZ ",
        "Composition": "Ofloxacin 200 mg + Ornidazole 500 mg TABLETS ",
        "Packing": "10x10 Blister ",
        "Mrp": 796.0,
        "Image-link": "https://i.ibb.co/mVdsQ9DN/Ofdin-OZ-10x10.png",
        "Visual-aid": "https://i.ibb.co/HDL8yvRM/OH-126-OFDIN-OZ-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 124,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "ONIE-P ",
        "Composition": "Nimesulide 100 mg Paracetamol 325 mg TABLETS ",
        "Packing": "10x10 Blister ",
        "Mrp": 365.0,
        "Image-link": "https://i.ibb.co/WNjhwkQQ/Onie-P-10x10.png",
        "Visual-aid": "https://i.ibb.co/TMtLKRDd/OH-128-ONIE-P-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 125,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NOOTROPIC",
        "Name": "OTAM ",
        "Composition": "Piracetam 800mg TABLETS",
        "Packing": "10x10 Blister ",
        "Mrp": 965.0,
        "Image-link": "https://i.ibb.co/jPd5DGhP/Otam-10x10.png",
        "Visual-aid": "https://i.ibb.co/vCSdS1cS/OH-134-OTAM-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 126,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "OTEL-40 ",
        "Composition": "Telmisartan 40mg  TABLETS",
        "Packing": "10x10 Strip Pack ",
        "Mrp": 750.0,
        "Image-link": "https://i.ibb.co/vvwHLMh5/Otel-40-10x10.png",
        "Visual-aid": "https://i.ibb.co/XZtP9XW0/OH-354-OTEL-40-VP-9-11-2024-NEW.jpg"
    },
    {
        "Id": 127,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "OTEL-AM ",
        "Composition": "Telmisartan 40mg +Amlodipine Besylate 5mg TABLETS",
        "Packing": "10x10 Strip Pack ",
        "Mrp": 1125.0,
        "Image-link": "https://i.ibb.co/hF24xz4b/Otel-Am-10x10.png",
        "Visual-aid": "https://i.ibb.co/C5cD5HMR/OH-353-OTEL-AM-VP-9-11-2024-NEW.jpg"
    },
    {
        "Id": 128,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "OTEL-H ",
        "Composition": "Telmisartan 40mg +Hydrochlorothiazide 12.5mg  TABLETS",
        "Packing": "10x10 Strip Pack ",
        "Mrp": 750.0,
        "Image-link": "https://i.ibb.co/mCrpsL3M/Otel-h-10x10.png",
        "Visual-aid": "https://i.ibb.co/zWRQ71JK/OH-352-OTEL-H-TAB-VP-9-11-2024-NEW.jpg"
    },
    {
        "Id": 129,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "PANTODIN ",
        "Composition": "Pantoprazole Sodium 40 mg  TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 0.0,
        "Image-link": "https://i.ibb.co/B25W56YZ/Pantodin-10x10.png",
        "Visual-aid": "https://i.ibb.co/ycGvyzd4/OH-125-PANTODIN-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 130,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "NSAIDS/ANALGESIC/PROTEOLYTIC",
        "Name": "PIRODIN ",
        "Composition": "Piroxicam 20 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 609.0,
        "Image-link": "https://i.ibb.co/0pvzcCQy/Pirodin-10x10.png",
        "Visual-aid": "https://i.ibb.co/z367nmH/OH-126-PIRODIN-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 131,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "RABEDIN ",
        "Composition": "Rabeprazole Sodium 20 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 534.0,
        "Image-link": "https://i.ibb.co/84PFJMVM/Rabedin-10x10.png",
        "Visual-aid": "https://i.ibb.co/QjbWZpvZ/OH-127-RABEDIN-D-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 132,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "RABEDIN-D ",
        "Composition": "Rabeprazole Sodium 20 mg + Domperidone 10 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 571.0,
        "Image-link": "https://i.ibb.co/mCH0swcD/Rabedin-D-10x10.png",
        "Visual-aid": "https://i.ibb.co/QjbWZpvZ/OH-127-RABEDIN-D-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 133,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "ROSCOBATE-40",
        "Composition": "Esomeprazole Magnesium Trihydrate 40mg  TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 731.0,
        "Image-link": "https://i.ibb.co/5V8nCVK/Roscobate-40-10x10.png",
        "Visual-aid": "https://i.ibb.co/8gJBmMtk/OH-341-ROSCOBATE-TAB-VP-9-1-2024-1.jpg"
    },
    {
        "Id": 134,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "ROSU-F",
        "Composition": "Rosuvastatin Calcium 10mg+Fenofibrate 160mg  TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 2156.0,
        "Image-link": "https://i.ibb.co/1fSZ2Qsc/Rosu-F-10x10.png",
        "Visual-aid": "https://i.ibb.co/M5Ng3bLM/OH-358-ROSU-F-TAB-VP-28-5-2025-NEW.jpg"
    },
    {
        "Id": 135,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "ROSU-10  ",
        "Composition": "Rosuvastatin Calcium 10mg  TABLETS ",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1856.25,
        "Image-link": "https://i.ibb.co/HpNDG6NV/Rosu10-10x10.png",
        "Visual-aid": "https://i.ibb.co/pBp9KNYH/OH-357-ROSU-10-TAB-VP-28-5-2025-NEW.jpg"
    },
    {
        "Id": 136,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-VERTIGO",
        "Name": "STAIN-16",
        "Composition": "Betahistine Dihydrochloride 16 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1021.9,
        "Image-link": "https://i.ibb.co/Mx0WKVW0/Stain-16-10x10.png",
        "Visual-aid": "https://i.ibb.co/LfPCw7m/OH-128-STAIN-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 137,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-VERTIGO",
        "Name": "STAIN-24",
        "Composition": "Betahistine Dihydrochloride 24mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1078.0,
        "Image-link": "https://i.ibb.co/SXPtfMK2/Stain-24-10x10.png",
        "Visual-aid": "https://i.ibb.co/8gsFZf5j/OH-363-STAIN-24-TAB-VP-28-5-2025-NEW.jpg"
    },
    {
        "Id": 138,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "ANTI-VERTIGO",
        "Name": "STAIN-8",
        "Composition": "Betahistine Dihydrochloride 8 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 609.0,
        "Image-link": "https://i.ibb.co/wFkkyFfL/Stain-8-10x10.png",
        "Visual-aid": "https://i.ibb.co/LfPCw7m/OH-128-STAIN-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 139,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "STEROIDS",
        "Name": "ZECOD-6 ",
        "Composition": "Deflazacort 6 mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1031.0,
        "Image-link": "https://i.ibb.co/qFYVjRcm/Zecod-6-10x10.png",
        "Visual-aid": "https://i.ibb.co/SDB3kPyv/OH-132-ZECOD-6-VP-final-17-6-2022.jpg"
    },
    {
        "Id": 140,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "ZINCODIN ",
        "Composition": "Multivitamins+ Multiminerals & Antioxidants  TABLETS",
        "Packing": "10x10 Alu Alu  ",
        "Mrp": 756.0,
        "Image-link": "https://i.ibb.co/YFvXPt86/Zincodin-10x10-2.png",
        "Visual-aid": "https://i.ibb.co/yBnsG2Mp/OH-76-ZINCODIN-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 141,
        "Category": "Orals",
        "Sub-category": "Tablets",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "ZINCODIN ",
        "Composition": "Multivitamins+ Multiminerals & Antioxidants  TABLETS",
        "Packing": "       Poly Foil Pack ",
        "Mrp": 578.0,
        "Image-link": "https://i.ibb.co/b5n9BKgw/Zincodin-10x10.png",
        "Visual-aid": "https://i.ibb.co/yBnsG2Mp/OH-76-ZINCODIN-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 142,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "CALCIUM & VITAMIN. D3 SUPPLEMENTS",
        "Name": "CALDIN MAX ",
        "Composition": "Calcium Phosphate 82mg+Vitamin D3 200 IU+Vitamin B12 2.5mcg  SUSPENSION ",
        "Packing": "200ml Bottle",
        "Mrp": 2381.0,
        "Image-link": "https://i.ibb.co/b5m7vyv1/Caldin-Max-200ml.png",
        "Visual-aid": "https://i.ibb.co/VchDSy1b/OH-346-CALDIN-MAX-VP-28-5-2024.jpg"
    },
    {
        "Id": 143,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "ANTI-ALLERGIC/ANTI ASTHMATIC",
        "Name": "MONTEDIN ",
        "Composition": "Montelukast Sodium 4mg+Levocetirizine Dihydrate 2.5mg SYRUP ",
        "Packing": "60ml Bottle ",
        "Mrp": 81.56,
        "Image-link": "https://i.ibb.co/VWwthLD6/Montedin-60ml.png",
        "Visual-aid": "https://i.ibb.co/4ngW4vvg/OH-113-MONTEDIN-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 144,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "EXPECTORANTS & ANTI TUSSIVE",
        "Name": "OCTUS ",
        "Composition": "Dextromethorphan HBR 10mg + Chlorpheniramine Maleate 2mg + Phenylephrine HCL 5mg SYRUP ",
        "Packing": "100ml Bottle",
        "Mrp": 82.0,
        "Image-link": "https://i.ibb.co/NgNGm8gR/Octus-100ml.png",
        "Visual-aid": "https://i.ibb.co/TDV4kYVj/OH-148-OCTUS-CF-SYRUP-VP-8-6-2022.jpg"
    },
    {
        "Id": 145,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "EXPECTORANTS & ANTI TUSSIVE",
        "Name": "OCTUS-CF ",
        "Composition": "Terbutaline Sulphate 1.25mg + Ambroxol HCI 15mg + Guaiphenesin 50mg + Menthol 2.5mg SYRUP ",
        "Packing": "100ml Bottle",
        "Mrp": 82.0,
        "Image-link": "https://i.ibb.co/Qv5nk6s8/Octus-CF-100ml.png",
        "Visual-aid": "https://i.ibb.co/TDV4kYVj/OH-148-OCTUS-CF-SYRUP-VP-8-6-2022.jpg"
    },
    {
        "Id": 146,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "CALCIUM & VITAMIN. D3 SUPPLEMENTS",
        "Name": "ODCARE -3 ",
        "Composition": "Cholecalciferol IP 60000 IU nullO SHOTS",
        "Packing": "4x5ml Vials",
        "Mrp": 75.0,
        "Image-link": "https://i.ibb.co/zh9fyLYC/Odcare-3-4x5ml.png",
        "Visual-aid": "https://i.ibb.co/nsmjB789/OH-350-ODCARE-2-nullO-SHOT-VP-8-11-2024-NEW-1.jpg"
    },
    {
        "Id": 147,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "MULTI-VITAMIN",
        "Name": "OPHY ",
        "Composition": "Lycopene 10% -2000mcg +Niacinamide 25mg +Vitamin B6 -1.5mg  +Vitamin B12-1mcg +Folic Acid 100mcg+selenium 35mcg++Zinc Gluconate 3mg+Iodine Potassium 100mcg+Copper 500mcg SYRUP ",
        "Packing": "200ml Bottle",
        "Mrp": 152.0,
        "Image-link": "https://i.ibb.co/C5YFj4k3/Ophy-200ml.png",
        "Visual-aid": "https://i.ibb.co/BVXWWNR1/OH-72-OPHY-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 148,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "DIGESTIVE ENZYME",
        "Name": "OTIZ ",
        "Composition": "Fungal Diastase 50mg +Pepsin 10mg SYRUP ",
        "Packing": "200ml Bottle",
        "Mrp": 135.0,
        "Image-link": "https://i.ibb.co/QjdygPg2/Otiz-200ml.png",
        "Visual-aid": "https://i.ibb.co/jZjbVtJn/OH-149-OTIZ-SYRUP-VP-8-6-2022.jpg"
    },
    {
        "Id": 149,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "DIGESTIVE ENZYME",
        "Name": "OTIZ-SF ",
        "Composition": "Fungal Diastase 50mg +Pepsin 10mg SYRUP ",
        "Packing": "200ml Bottle",
        "Mrp": 134.0,
        "Image-link": "https://i.ibb.co/qYSRZxV0/Otiz-SF-200ml.png",
        "Visual-aid": "https://i.ibb.co/jZjbVtJn/OH-149-OTIZ-SYRUP-VP-8-6-2022.jpg"
    },
    {
        "Id": 150,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "MULTI-VITAMIN",
        "Name": "ZINCODIN ",
        "Composition": "Antioxidants +Multivitamin+ Multiminral & Cyanocobalamin SYRUP ",
        "Packing": "200ml Bottle",
        "Mrp": 145.0,
        "Image-link": "https://i.ibb.co/VYVCsVjt/Zincodin-200ml.png",
        "Visual-aid": "https://i.ibb.co/r2KhFb2X/OH-150-ZINCODIN-SYRUP-VP-8-6-2022.jpg"
    },
    {
        "Id": 151,
        "Category": "Orals",
        "Sub-category": "Syrup",
        "Sub-Sub-Category": "MULTI-VITAMIN",
        "Name": "ZINCODIN",
        "Composition": "Multivitamins, Multiminrals & L-Lysine DROPS",
        "Packing": "30ml Bottle",
        "Mrp": 54.0,
        "Image-link": "https://i.ibb.co/jPNp5y0g/Zincodin-drop-30ml.png",
        "Visual-aid": "https://i.ibb.co/r2KhFb2X/OH-150-ZINCODIN-SYRUP-VP-8-6-2022.jpg"
    },
    {
        "Id": 152,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "CALCIUM & VIT. D SUPPLEMENTS",
        "Name": "CALDIN ",
        "Composition": "Calcitriol 0.25Mcg+ Calcium Carbonate500mg, & Zinc 7.5mg  SOFTGEL CALSULES",
        "Packing": "10x10 Blister ",
        "Mrp": 871.0,
        "Image-link": "https://i.ibb.co/JwwFsmm3/Caldin-10x10.png",
        "Visual-aid": "https://i.ibb.co/MkGM7Kn6/OH-142-CALDIN-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 153,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "CALCIUM & VIT. D SUPPLEMENTS",
        "Name": "CALDIN K2 -7",
        "Composition": "Calcitriol 0.25mcg+Calcium Citrate Maleate 500mg+ Vitamin K2-7 45mcg+Methylcobalamin 1500mcg+Zinc Oxide 7.5mg+Magnesium Oxide 20mg+ L-Methyl Folate 800mcg SOFTGEL CALSULES",
        "Packing": "10x1x10 Kit Pack ",
        "Mrp": 2887.0,
        "Image-link": "https://i.ibb.co/FbGV3KwV/Caldin-K2-7.png",
        "Visual-aid": "https://i.ibb.co/rRWNcLNb/OH-75-CALDIN-K2-7-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 154,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "CALCIUM & VITAMIN. D3 SUPPLEMENTS",
        "Name": "CALDIN MAX ",
        "Composition": "Calcium Phosphate 82mg+Vitamin D3 200 IU+Vitamin B12 2.5mcg  SUSPENSION ",
        "Packing": "200ml Bottle",
        "Mrp": 2381.0,
        "Image-link": "https://i.ibb.co/q34X55rK/Caldin-Max-1x10.png",
        "Visual-aid": "https://i.ibb.co/GvtVHVqh/OH-74-CALDIN-MAX-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 155,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "MEGADIN-5G ",
        "Composition": "Omega-3 Fatty Acid 90mg+ Green Tea Extract 10mg+Ginkgo Biloba Extract 10mg+ Ginseng Extract42.5mg+Grape Seed Extract15mg+ Vitamins,Minerals & Trace Elements SOFTGEL CALSULES",
        "Packing": "10x1x10 Blister ",
        "Mrp": 1837.5,
        "Image-link": "https://i.ibb.co/B5WrSS29/Megadin-5g.png",
        "Visual-aid": "https://i.ibb.co/b5tDpScz/OH-73-MEGADIN-5-G-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 156,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "COUGH SUPPRESSANT",
        "Name": "OCTUS ",
        "Composition": "Dextromethorphan Hydrobromide 10mg, Phenylephrine Hydrochloride 5mg, Chlorpheniramine Maleate 2mg  SOFTGEL CALSULES",
        "Packing": "10x1x4 Kit Pack ",
        "Mrp": 562.5,
        "Image-link": "https://i.ibb.co/N6bsfWxM/Octus-1x10.png",
        "Visual-aid": "https://i.ibb.co/TMJFs9vy/OH-146-OCTUS-CAPS-VP-8-6-2022.jpg"
    },
    {
        "Id": 157,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "CALCIUM & VIT. D SUPPLEMENTS",
        "Name": "OD3 ",
        "Composition": "Cholecalciferol IP 60000 IU SOFTGEL CALSULES",
        "Packing": "10x1x4 Kit Pack ",
        "Mrp": 1284.0,
        "Image-link": "https://i.ibb.co/JwfTVN5J/OD3-1x4.png",
        "Visual-aid": "https://i.ibb.co/d0Zy53Bp/OH-145-OD3-CAPS-VP-FINAL-22-6-2022.jpg"
    },
    {
        "Id": 158,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "OPHY ",
        "Composition": "Lycopene, Methylcobalamin, Multivitamins & Multiminerals SOFTGEL CALSULES",
        "Packing": "10x10 Blister ",
        "Mrp": 1284.0,
        "Image-link": "https://i.ibb.co/mVRvsQcz/Ophy-1x10.png",
        "Visual-aid": "https://i.ibb.co/BVXWWNR1/OH-72-OPHY-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 159,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "VICODIN WOMEN ",
        "Composition": "Multivitamin,Multimineral & Antioxidants SOFTGEL CALSULES",
        "Packing": "2x15 Blister",
        "Mrp": 0.0,
        "Image-link": "https://i.ibb.co/mrgsqgQ7/Vicodin-2x15.png",
        "Visual-aid": null
    },
    {
        "Id": 160,
        "Category": "Orals",
        "Sub-category": "Soft Geletine",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "VICODIN MEN ",
        "Composition": "Ginseng +Multivitamins+Minerals  SOFTGEL CALSULES",
        "Packing": "2x15 Blister",
        "Mrp": 0.0,
        "Image-link": "https://i.ibb.co/zh2rs7Wp/Vicodin-Men-2x15-2.png",
        "Visual-aid": null
    },
    {
        "Id": 161,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "PANTODIN-DSR ",
        "Composition": "Pantoprazole Sodium 40 mg + Domperidone 30 mg SR TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 646.0,
        "Image-link": "https://i.ibb.co/WNCpzK75/Pantodin-Dsr.png",
        "Visual-aid": "https://i.ibb.co/h1gr8yXN/OH-139-PANTODIN-DSR-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 162,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "PANTODIN LSR  ",
        "Composition": "Pantoprazole Sodium40mg+ Levosulpiride (sr) 75mg TABLETS",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1903.0,
        "Image-link": "https://i.ibb.co/gLvHb3X4/Pantodin-Lsr.png",
        "Visual-aid": "https://i.ibb.co/KcLVFQ41/OH-141-RABEDIN-LSR-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 163,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "RABEDIN-DSR",
        "Composition": "Rabeprazole Sodium 20 mg + Domperidone 30 mg SR CAPSULES",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 984.0,
        "Image-link": "https://i.ibb.co/cKNMTm9P/Rabedin-Dsr.png",
        "Visual-aid": "https://i.ibb.co/LDqPB621/OH-140-RABEDIN-DSR-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 164,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "RABEDIN-LSR",
        "Composition": "Rabeprazole Sodium 20 mg + Levosulpiride 75 mg (SR) CAPSULES",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1931.0,
        "Image-link": "https://i.ibb.co/V0KRm399/Rabedin-Lsr.png",
        "Visual-aid": "https://i.ibb.co/KcLVFQ41/OH-141-RABEDIN-LSR-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 165,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "PROTON-PUMP-INHIBITOR",
        "Name": "ROSCOBATE ",
        "Composition": "Esomeprazole 40 mg + Domperidone 30 mg SR CAPSULES",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1125.0,
        "Image-link": "https://i.ibb.co/yBnqKXBS/Roscobate.png",
        "Visual-aid": "https://i.ibb.co/LhsCpt6R/OH-142-ROSCOBATE-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 166,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "ROSU-10 GOLD Cap. ",
        "Composition": "Rosuvastatin Calcium 10mg +Aspirin 75mg+ Clopidogrel Bisulphate 75mg",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1968.75,
        "Image-link": "https://i.ibb.co/wrp0w2XK/Rosu-10-Gold.png",
        "Visual-aid": "https://i.ibb.co/vxq7B9RN/OH-361-ROSU-10-GOLD-TAB-VP-28-5-2025-NEW-1.jpg"
    },
    {
        "Id": 167,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "ROSU-20 GOLD Cap. ",
        "Composition": "Rosuvastatin Calcium 20mg +Aspirin 75mg+ Clopidogrel Bisulphate 75mg",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 2906.25,
        "Image-link": "https://i.ibb.co/pvMkQWdt/Rosu-20-Gold.png",
        "Visual-aid": "https://i.ibb.co/vxq7B9RN/OH-361-ROSU-10-GOLD-TAB-VP-28-5-2025-NEW-1.jpg"
    },
    {
        "Id": 168,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "ANGIOTENSIN 2 RECEPTOR BLOCKE ",
        "Name": "ROSU-CV 10 Cap. ",
        "Composition": "Rosuvastatin Calcium 10mg + Clopidogrel Bisulphate 75mg",
        "Packing": "10x10 Alu Alu ",
        "Mrp": 1875.0,
        "Image-link": "https://i.ibb.co/xthhBLmY/Rosu-cv10.png",
        "Visual-aid": "https://i.ibb.co/gLFRPm86/OH-362-ROSU-CV10-TAB-VP-28-5-2025-NEW.jpg"
    },
    {
        "Id": 169,
        "Category": "Orals",
        "Sub-category": "Capsules",
        "Sub-Sub-Category": "FOOD SUPPLEMENTS",
        "Name": "VICOMIN-21",
        "Composition": "Ginseng Ashwagandha, Multivitamins & Minerals CAPSULES",
        "Packing": "10x1x10 Blister ",
        "Mrp": 934.0,
        "Image-link": "https://i.ibb.co/s9hDfpDy/Vicomin-21.png",
        "Visual-aid": "https://i.ibb.co/KjHJ59wq/OH-144-VICOMIN-21-CAPS-VP-FINAL-17-6-2022.jpg"
    },
    {
        "Id": 170,
        "Category": "Orals",
        "Sub-category": "Suppliments",
        "Sub-Sub-Category": "PROTEIN SUPPLEMENT",
        "Name": "ZINCODIN",
        "Composition": "Fortified With Protein Vitamin & Minerals Vanilla Flavour PROTEIN POWDER ",
        "Packing": "200gm Jar",
        "Mrp": 249.0,
        "Image-link": "https://i.ibb.co/GfvRPT8q/Zincodin-chocolate.png",
        "Visual-aid": "https://i.ibb.co/wrBrGqB5/OH-151-ZINCODIN-PROTEIN-POWDER-VP-8-6-2022.jpg"
    },
    {
        "Id": 171,
        "Category": "Orals",
        "Sub-category": "Suppliments",
        "Sub-Sub-Category": "PROTEIN SUPPLEMENT",
        "Name": "ZINCODIN",
        "Composition": "Fortified With Protein Vitamin & Minerals Chocolate Flavour PROTEIN POWDER ",
        "Packing": "200gm Jar",
        "Mrp": 249.0,
        "Image-link": "https://i.ibb.co/3ySnbZgp/Zincodin-vanilla.png",
        "Visual-aid": "https://i.ibb.co/wrBrGqB5/OH-151-ZINCODIN-PROTEIN-POWDER-VP-8-6-2022.jpg"
    },
    {
        "Id": 172,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "ABRACIN ",
        "Composition": "Mupirocin  2.0% w/w OINTMENT",
        "Packing": "5gm Tube ",
        "Mrp": 107.81,
        "Image-link": "https://i.ibb.co/1f6P1t4T/Abracin-5gm.png",
        "Visual-aid": "https://i.ibb.co/q3H6HkP9/OH-81-ABRACIN-5-GM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 173,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "ACRID GEL",
        "Composition": "Clindamycin Phosphate 1%w/w+ Nicotinamide 4%w/w GEL ",
        "Packing": "10gm Tube ",
        "Mrp": 87.19,
        "Image-link": "https://i.ibb.co/d48gwG34/Acrid-gel-10gm.png",
        "Visual-aid": "https://i.ibb.co/BVkVckCs/OH-84-ACRID-GEL-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 174,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "CLODIN ",
        "Composition": "Clobetasol Propionate  0.05% w/w+Neomycin Sulphate IP 0.5%w/w + Miconazole NitrateIP 2%w/w CREAM ",
        "Packing": "20gm Tube ",
        "Mrp": 84.0,
        "Image-link": "https://i.ibb.co/zHG7dHQ6/Clodin-20gm.png",
        "Visual-aid": "https://i.ibb.co/1Jnj4zRF/OH-85-CLODIN-CREAM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 175,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "D-4",
        "Composition": "Ciprofloxacin HCL 1.0%w/w+Metronidazole Benzoate 1.0%w/w+Terbinafine HCL 1.0%w/w+Clobetasol Propionate 0.05%w/w Cream ",
        "Packing": "15gm Tube ",
        "Mrp": 79.69,
        "Image-link": "https://i.ibb.co/RpTVQfcF/D-4-15gm.png",
        "Visual-aid": "https://i.ibb.co/R4spmRCm/OH-359-D-4-CREAM-VVP-28-5-2025-NEW.jpg"
    },
    {
        "Id": 176,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "SKIN CARE CREAM",
        "Name": "F CARE ",
        "Composition": "Aloe Vera 10%+Vitamin E 0.5% CREAM ",
        "Packing": "50gm Tube ",
        "Mrp": 123.75,
        "Image-link": "https://i.ibb.co/MbJVp32/F-Care-50gm.png",
        "Visual-aid": "https://i.ibb.co/Sw0SMtMx/OH-86-F-CARE-CREAM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 177,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "FACID-B",
        "Composition": "Fusidic Acid 2%w.w+ Beclomethasone Dipropionate 0.025%w/w+ Chlorocresol 0.1% w/w CREAM ",
        "Packing": "10gm Tube ",
        "Mrp": 65.63,
        "Image-link": "https://i.ibb.co/B5YwSQYw/Facid-B-10gm.png",
        "Visual-aid": "https://i.ibb.co/hRM27n2G/OH-87-FACID-B-CREAM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 178,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "FLUTAMIC",
        "Composition": "Fluocinolone Acetonide 0.025%+Neomycin Sulphate 0.5%w/w +Miconazole Nitrate 2% w/w CREAM ",
        "Packing": "10gm Tube ",
        "Mrp": 56.25,
        "Image-link": "https://i.ibb.co/yBSxTxtK/Flutamic-10gm.png",
        "Visual-aid": "https://i.ibb.co/mVhJJ7Lp/OH-88-FLUTAMIC-CREAM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 179,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANALGESIC",
        "Name": "Gel OD ",
        "Composition": "Diclofenac Diethylamine 1.16%w/w+ Linseed Oil 3.00% w/w + Methyl Salicylate 10.%w/w + Menthol 5%w/w GEL ",
        "Packing": "30gm Tube ",
        "Mrp": 97.0,
        "Image-link": "https://i.ibb.co/LhDyxP8z/Gel-Od-30gm.png",
        "Visual-aid": "https://i.ibb.co/d0Sk5DRg/OH-90-GEL-OD-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 180,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANALGESIC",
        "Name": "GEL-CEKLO ",
        "Composition": "Aceclofenac 1.5%w/w+ Linseed Oil 3.00% w/w + Methyl Salicylate 10.00%w/w + Capsaisin 0.01% w/w+ Menthol 5.00%w/w GEL ",
        "Packing": "30gm Tube ",
        "Mrp": 92.81,
        "Image-link": "https://i.ibb.co/hxwdN13M/Gel-Ceklo-30gm.png",
        "Visual-aid": "https://i.ibb.co/mrXj4X1q/OH-89-CEKLO-GEL-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 181,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "LUNIDERM ",
        "Composition": "Luliconazole 1% w/w Methylparaben 0.14%w/w+Benzyl Alcohol 1%w/w CREAM ",
        "Packing": "20gm Tube ",
        "Mrp": 128.44,
        "Image-link": "https://i.ibb.co/gbTYjjbm/Luniderm-20gm.png",
        "Visual-aid": "https://i.ibb.co/MkDx1twT/OH-91-LUNIDERM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 182,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "CORTICOSTEROIDS",
        "Name": "MOTIN",
        "Composition": "Mometasone Furoate 0.1% W/W CREAM ",
        "Packing": "20gm Tube ",
        "Mrp": 97.5,
        "Image-link": "https://i.ibb.co/YBwDYWjx/Motin-20gm.png",
        "Visual-aid": "https://i.ibb.co/21YYLvkG/OH-92-MOTIN-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 183,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-BACTERIAL/ANTI-FUNGAL",
        "Name": "ODIDERM ",
        "Composition": "Belclomethasone Dipropionate 0.025% w/w+Clotrimazole  1% w/w +Neomycin Sulphate0.5% w/w Chlorocresol 0.1% w/w  CREAM ",
        "Packing": "10gm Tube ",
        "Mrp": 66.56,
        "Image-link": "https://i.ibb.co/99BJvRfQ/Odiderm-10g.png",
        "Visual-aid": "https://i.ibb.co/W1VpTpx/OH-93-ODIDERM-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 184,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI DANDRUFF SHAMPOO",
        "Name": "OKET ",
        "Composition": "Ketoconazole 2% w/v SHAMPOO",
        "Packing": "60ml Jar ",
        "Mrp": 220.31,
        "Image-link": "https://i.ibb.co/QjNV63hx/Oket-60ml.png",
        "Visual-aid": "https://i.ibb.co/qv1bLv0/OH-96-OKET-SHAMPOO-VP-FINAL-16-62022.jpg"
    },
    {
        "Id": 185,
        "Category": "Skin Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "ANTI-SCABIES",
        "Name": "PEARM ",
        "Composition": "Permethrin Lotion 5% v/v LOTION ",
        "Packing": "50ml Jar ",
        "Mrp": 53.55,
        "Image-link": "https://i.ibb.co/JwrYDwzQ/Pearm-50ml.png",
        "Visual-aid": "https://i.ibb.co/Y4DND4Jx/OH-97-PEARM-LOTION-VP-FINAL-16-6-2022.jpg"
    },
    {
        "Id": 186,
        "Category": "Dental Range",
        "Sub-category": "Ointments",
        "Sub-Sub-Category": "DENTAL",
        "Name": "O-32 ",
        "Composition": "Potassium Nitrate 5% +Sodium Monofluorophosphate 0.7% TOOTHPASTE ",
        "Packing": "50gm Tube ",
        "Mrp": 78.75,
        "Image-link": "https://i.ibb.co/5hcdrs5t/O-32-50gm.png",
        "Visual-aid": "https://i.ibb.co/TBqBG6tx/OH-81-O-32-TOOTH-PASTE-VP-FINAL-16-6-2022.jpg"
    }
]

export default PRODUCTS;